# Generated by Django 3.2.18 on 2023-11-17 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_loose_fk.constraints
import django_loose_fk.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("klantinteracties", "0004_auto_20231110_0735"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactgegevens",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_relation_url", models.URLField(blank=True)),
                (
                    "relation",
                    django_loose_fk.fields.FkOrURLField(
                        blank=False,
                        fk_field="_relation",
                        null=False,
                        url_field="_relation_url",
                    ),
                ),
                (
                    "_relation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.partijidentificator",
                    ),
                ),
            ],
            options={
                "verbose_name": "contactgegevens",
                "verbose_name_plural": "contactgegevens",
            },
        ),
        migrations.CreateModel(
            name="Persoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adres_adresregel1",
                    models.CharField(
                        blank=True,
                        help_text="Eerste deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="adresregel 1",
                    ),
                ),
                (
                    "adres_adresregel2",
                    models.CharField(
                        blank=True,
                        help_text="Tweede deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="adresregel 2",
                    ),
                ),
                (
                    "adres_adresregel3",
                    models.CharField(
                        blank=True,
                        help_text="Derde deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="adresregel 3",
                    ),
                ),
                (
                    "adres_land",
                    models.CharField(
                        blank=True,
                        help_text="Een code, opgenomen in Tabel 34, Landentabel, die het land (buiten Nederland) aangeeft alwaar de ingeschrevene verblijft.",
                        max_length=4,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=4),
                            django.core.validators.validate_integer,
                        ],
                        verbose_name="land",
                    ),
                ),
                (
                    "land_code",
                    models.CharField(
                        blank=True,
                        help_text="adres code",
                        max_length=255,
                        verbose_name="code",
                    ),
                ),
                (
                    "geboortedatum",
                    models.DateField(
                        help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21",
                        verbose_name="geboortedatum",
                    ),
                ),
                (
                    "overlijdensdatum",
                    models.DateField(
                        blank=True,
                        help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21",
                        verbose_name="overlijdensdatum",
                    ),
                ),
                (
                    "geslachtsnaam",
                    models.CharField(
                        help_text="De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels zijn afgesplitst. Gebruik van de wildcard is toegestaan bij invoer van ten minste 3 letters. Zoeken met tekstvelden is case-insensitive.",
                        max_length=200,
                        verbose_name="geslachtsnaam",
                    ),
                ),
                (
                    "geslacht",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Man"), ("v", "Vrouw"), ("o", "Overig")],
                        help_text="Geeft aan dat de persoon een man of een vrouw is, of dat het geslacht (nog) onbekend is.",
                        max_length=1,
                        verbose_name="geslacht",
                    ),
                ),
                (
                    "voorvoegsel",
                    models.CharField(
                        blank=True,
                        help_text="Deel van de geslachtsnaam dat vooraf gaat aan de rest van de geslachtsnaam. Zoeken met tekstvelden is case-insensitive.",
                        max_length=10,
                        verbose_name="voorvoegsel",
                    ),
                ),
                (
                    "voornamen",
                    models.CharField(
                        blank=True,
                        help_text="De verzameling namen die, gescheiden door spaties, aan de geslachtsnaam voorafgaat. Gebruik van de wildcard is toegestaan. Zoeken met tekstvelden is case-insensitive.",
                        max_length=200,
                        verbose_name="voornamen",
                    ),
                ),
                (
                    "contactgegevens",
                    models.ForeignKey(
                        help_text="De contact gegevens van het huidige persoon",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contactgegevens.contactgegevens",
                        verbose_name="contactgegevens",
                    ),
                ),
            ],
            options={
                "verbose_name": "persoon",
                "verbose_name_plural": "personen",
            },
        ),
        migrations.CreateModel(
            name="Organisatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adres_adresregel1",
                    models.CharField(
                        blank=True,
                        help_text="Eerste deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="adresregel 1",
                    ),
                ),
                (
                    "adres_adresregel2",
                    models.CharField(
                        blank=True,
                        help_text="Tweede deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="adresregel 2",
                    ),
                ),
                (
                    "adres_adresregel3",
                    models.CharField(
                        blank=True,
                        help_text="Derde deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="adresregel 3",
                    ),
                ),
                (
                    "adres_land",
                    models.CharField(
                        blank=True,
                        help_text="Een code, opgenomen in Tabel 34, Landentabel, die het land (buiten Nederland) aangeeft alwaar de ingeschrevene verblijft.",
                        max_length=4,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=4),
                            django.core.validators.validate_integer,
                        ],
                        verbose_name="land",
                    ),
                ),
                (
                    "land_code",
                    models.CharField(
                        blank=True,
                        help_text="adres code",
                        max_length=255,
                        verbose_name="code",
                    ),
                ),
                (
                    "handelsnaam",
                    models.CharField(
                        help_text="De naam waaronder een bedrijf of vestiging handelt.",
                        max_length=255,
                        verbose_name="handelsnaam",
                    ),
                ),
                (
                    "oprichtingsdatum",
                    models.DateField(
                        blank=True,
                        help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21",
                        verbose_name="oprichtingsdatum",
                    ),
                ),
                (
                    "opheffingsdatum",
                    models.DateField(
                        blank=True,
                        help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21",
                        verbose_name="opheffingsdatum",
                    ),
                ),
                (
                    "contactgegevens",
                    models.ForeignKey(
                        help_text="De contact gegevens van de huidige organisatie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contactgegevens.contactgegevens",
                        verbose_name="contactgegevens",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisatie",
                "verbose_name_plural": "organisaties",
            },
        ),
        migrations.AddConstraint(
            model_name="contactgegevens",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="contactgegevens",
                fk_field="_relation",
                model_name="contactgegevens",
                url_field="_relation_url",
            ),
        ),
    ]
