# Generated by Django 3.2.23 on 2024-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactgegevens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisatie",
            name="adres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=255,
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=255,
                verbose_name="nummeraanduiding ID",
            ),
        ),
    ]
