# Generated by Django 4.2.15 on 2024-12-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactgegevens", "0002_auto_20240126_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persoon",
            name="overlijdensdatum",
            field=models.DateField(
                blank=True,
                help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21",
                null=True,
                verbose_name="overlijdensdatum",
            ),
        ),
    ]
