# Generated by Django 4.2.15 on 2025-01-09 09:22

import json
import logging
import openklant.utils.validators
from django.core.management import CommandError
from django.db import migrations, models
from django.db.models.functions import Length

logger = logging.getLogger(__name__)


def _check_nummeraanduiding_length(apps, schema_editor):

    Organisatie = apps.get_model("contactgegevens", "Organisatie")
    Persoon = apps.get_model("contactgegevens", "Persoon")

    organisatie_queryset = Organisatie.objects.annotate(
        length=Length("adres_nummeraanduiding_id")
    ).filter(length__gt=16)

    logger.info("--- START Organisatie INFO ---")
    logger.info(
        "Found %s records for Organisatie that have adres_nummeraanduiding_id length > 16 chars",
        organisatie_queryset.count(),
    )

    for record in organisatie_queryset:
        logger.warning(
            json.dumps(
                {
                    "pk": record.pk,
                    "uuid": str(record.uuid),
                    "adres_nummeraanduiding_id": record.adres_nummeraanduiding_id,
                }
            )
        )

    logger.info("--- END Organisatie INFO ---")

    persoon_queryset = Persoon.objects.annotate(
        length=Length("adres_nummeraanduiding_id")
    ).filter(length__gt=16)

    logger.info("--- START Persoon INFO ---")
    logger.info(
        "Found %s records for Persoon that have adres_nummeraanduiding_id length > 16 chars",
        persoon_queryset.count(),
    )

    for record in persoon_queryset:
        logger.warning(
            json.dumps(
                {
                    "pk": record.pk,
                    "uuid": str(record.uuid),
                    "adres_nummeraanduiding_id": record.adres_nummeraanduiding_id,
                }
            )
        )
    logger.info("--- END Persoon INFO ---")

    if organisatie_queryset or persoon_queryset:
        raise CommandError(
            "The migration cannot proceed due to data that doesn't comply with the model's requirements."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contactgegevens", "0003_alter_persoon_overlijdensdatum"),
    ]

    operations = [
        migrations.RunPython(
            code=_check_nummeraanduiding_length,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
    ]
