# Generated by Django 4.2.15 on 2025-01-09 09:22

from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("contactgegevens", "0003_alter_persoon_overlijdensdatum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisatie",
            name="adres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
    ]
