# Generated by Django 4.2.15 on 2025-01-09 15:19
import logging
import django.core.validators
from django.db import migrations, models
import openklant.utils.validators

from openklant.utils.converters import nl_code_to_iso_code_country_converter

logger = logging.getLogger(__name__)


def _update_records(records, class_name):
    logger.info("Start updating records for %s", class_name)
    for record in records:
        updated = False
        if record.adres_land:
            value = nl_code_to_iso_code_country_converter(record.adres_land)
            if not value:
                logger.warning(
                    "%s object (pk: %s, uuid: %s) has no match for the nl_code '%s'",
                    class_name,
                    record.pk,
                    record.uuid,
                    record.adres_land,
                )
            record.adres_land = value
            updated = True
        if record.land:
            value = nl_code_to_iso_code_country_converter(record.land)
            if not value:
                logger.warning(
                    "%s object (pk: %s, uuid: %s) has no match for the nl_code '%s'",
                    class_name,
                    record.pk,
                    record.uuid,
                    record.land,
                )
            record.land = value
            updated = True
        if updated:
            logger.debug(
                "Object %s pk: %s uuid %s updated",
                class_name,
                record.pk,
                record.uuid,
            )
            record.save()
    logger.info("Records update finished")


def _update_country_code(apps, schema_editor):
    Organisatie = apps.get_model("contactgegevens", "Organisatie")
    Persoon = apps.get_model("contactgegevens", "Persoon")

    _update_records(Organisatie.objects.all(), "Organisatie")
    _update_records(Persoon.objects.all(), "Persoon")


class Migration(migrations.Migration):

    dependencies = [
        ("contactgegevens", "0003_alter_persoon_overlijdensdatum"),
    ]

    operations = [
        migrations.RunPython(
            code=_update_country_code,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
    ]
