# Generated by Django 4.2.17 on 2025-02-11 13:52

import django.core.validators
from django.db import migrations, models
import openklant.utils.validators


def handle_null_values(apps, schema_editor):
    Organisatie = apps.get_model("contactgegevens", "Organisatie")
    Persoon = apps.get_model("contactgegevens", "Persoon")

    Organisatie.objects.filter(
        adres_huisnummer__isnull=True,
        adres_huisnummertoevoeging__isnull=True,
        adres_postcode__isnull=True,
        adres_stad__isnull=True,
        adres_straatnaam__isnull=True,
    ).update(
        adres_huisnummer="",
        adres_huisnummertoevoeging="",
        adres_postcode="",
        adres_stad="",
        adres_straatnaam="",
    )

    Persoon.objects.filter(
        adres_huisnummer__isnull=True,
        adres_huisnummertoevoeging__isnull=True,
        adres_postcode__isnull=True,
        adres_stad__isnull=True,
        adres_straatnaam__isnull=True,
    ).update(
        adres_huisnummer="",
        adres_huisnummertoevoeging="",
        adres_postcode="",
        adres_stad="",
        adres_straatnaam="",
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "contactgegevens",
            "0005_alter_organisatie_adres_nummeraanduiding_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisatie",
            name="adres_huisnummer",
            field=models.CharField(
                blank=True,
                help_text="Huisnummer van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                null=True,
                max_length=5,
                validators=[django.core.validators.validate_integer],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_huisnummertoevoeging",
            field=models.CharField(
                blank=True,
                help_text="Huisnummertoevoeging van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=20,
                null=True,
                verbose_name="huisnummertoevoeging",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=6,
                null=True,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige postcode",
                        regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_stad",
            field=models.CharField(
                blank=True,
                help_text="Stad van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                null=True,
                verbose_name="stad",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_straatnaam",
            field=models.CharField(
                blank=True,
                help_text="Straatnaam van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                null=True,
                verbose_name="straatnaam",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_huisnummer",
            field=models.CharField(
                blank=True,
                help_text="Huisnummer van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                null=True,
                max_length=5,
                validators=[django.core.validators.validate_integer],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_huisnummertoevoeging",
            field=models.CharField(
                blank=True,
                help_text="Huisnummertoevoeging van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=20,
                null=True,
                verbose_name="huisnummertoevoeging",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=6,
                null=True,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige postcode",
                        regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_stad",
            field=models.CharField(
                blank=True,
                help_text="Stad van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                null=True,
                verbose_name="stad",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_straatnaam",
            field=models.CharField(
                blank=True,
                help_text="Straatnaam van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                null=True,
                verbose_name="straatnaam",
            ),
        ),
        migrations.RunPython(
            code=handle_null_values,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_huisnummer",
            field=models.CharField(
                blank=True,
                help_text="Huisnummer van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=5,
                validators=[django.core.validators.validate_integer],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_huisnummertoevoeging",
            field=models.CharField(
                blank=True,
                help_text="Huisnummertoevoeging van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=20,
                verbose_name="huisnummertoevoeging",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=6,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige postcode",
                        regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_stad",
            field=models.CharField(
                blank=True,
                help_text="Stad van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="stad",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="adres_straatnaam",
            field=models.CharField(
                blank=True,
                help_text="Straatnaam van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="straatnaam",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_huisnummer",
            field=models.CharField(
                blank=True,
                help_text="Huisnummer van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=5,
                validators=[django.core.validators.validate_integer],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_huisnummertoevoeging",
            field=models.CharField(
                blank=True,
                help_text="Huisnummertoevoeging van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=20,
                verbose_name="huisnummertoevoeging",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=6,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige postcode",
                        regex="^[1-9][0-9]{3} ?[a-zA-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_stad",
            field=models.CharField(
                blank=True,
                help_text="Stad van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="stad",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_straatnaam",
            field=models.CharField(
                blank=True,
                help_text="Straatnaam van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="straatnaam",
            ),
        ),
    ]
