# Generated by Django 4.2.17 on 2025-02-27 10:22

import django.core.validators
from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "contactgegevens",
            "0005_alter_organisatie_adres_nummeraanduiding_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisatie",
            name="land",
        ),
        migrations.RemoveField(
            model_name="persoon",
            name="land",
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_huisnummer",
            field=models.CharField(
                blank=True,
                help_text="Huisnummer van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=5,
                validators=[django.core.validators.validate_integer],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_huisnummertoevoeging",
            field=models.CharField(
                blank=True,
                help_text="Huisnummertoevoeging van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=20,
                verbose_name="huisnummertoevoeging",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige postcode", regex="^[1-9][0-9]{3} [A-Z]{2}$"
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_stad",
            field=models.CharField(
                blank=True,
                help_text="Stad van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="stad",
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="adres_straatnaam",
            field=models.CharField(
                blank=True,
                help_text="Straatnaam van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="straatnaam",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_huisnummer",
            field=models.CharField(
                blank=True,
                help_text="Huisnummer van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=5,
                validators=[django.core.validators.validate_integer],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_huisnummertoevoeging",
            field=models.CharField(
                blank=True,
                help_text="Huisnummertoevoeging van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=20,
                verbose_name="huisnummertoevoeging",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige postcode", regex="^[1-9][0-9]{3} [A-Z]{2}$"
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_stad",
            field=models.CharField(
                blank=True,
                help_text="Stad van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="stad",
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="adres_straatnaam",
            field=models.CharField(
                blank=True,
                help_text="Straatnaam van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=255,
                verbose_name="straatnaam",
            ),
        ),
    ]
