# Generated by Django 4.2.20 on 2025-05-13 08:53

from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "contactgegevens",
            "0006_remove_organisatie_land_remove_persoon_land_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisatie",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="adres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
    ]
