# Generated by Django 2.2.24 on 2021-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klanten", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="klant",
            name="aanmaakkanaal",
            field=models.CharField(
                blank=True,
                help_text="Het communicatiekanaal waarlangs de klant is aangemaakt.",
                max_length=50,
            ),
        ),
    ]
