# Generated by Django 2.2.24 on 2021-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klanten", "0002_klant_aanmaakkanaal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klant",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="Het label of etiket dat aan de specifieke informatiebron, zoals een webpagina, een bestand of een plaatje op internet is toegewezen waar de KLANT in de regel op het internet vindbaar is.",
                max_length=1000,
                verbose_name="Website URL",
            ),
        ),
    ]
