# Generated by Django 3.2.18 on 2023-10-10 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partij",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de betrokkene bij klantcontact.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "nummer",
                    models.PositiveIntegerField(
                        help_text="Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke partij aan te duiden.",
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999)
                        ],
                        verbose_name="Nummer",
                    ),
                ),
                (
                    "interne_notitie",
                    models.CharField(
                        blank=True,
                        help_text="Mededelingen, aantekeningen of bijzonderheden over de partij, bedoeld voor intern gebruik.",
                        max_length=1000,
                        verbose_name="Interne notitie",
                    ),
                ),
                (
                    "soort_partij",
                    models.CharField(
                        choices=[
                            ("persoon", "Persoon"),
                            ("organisatie", "Organisatie"),
                            ("contactpersoon", "Contactpersoon"),
                        ],
                        help_text="Geeft aan van welke specifieke soort partij sprake is.",
                        max_length=14,
                        verbose_name="Soort partij",
                    ),
                ),
                (
                    "indicatie_geheimhouding",
                    models.BooleanField(
                        help_text="Geeft aan of de verstrekker van partijgegevens heeft aangegeven dat deze gegevens als geheim beschouwd moeten worden.",
                        verbose_name="Indicatie geheimhouding",
                    ),
                ),
                (
                    "voorkeurskanaal",
                    models.CharField(
                        blank=True,
                        help_text="Kanaal dat de partij bij voorkeur gebruikt voor contact met de gemeente.",
                        max_length=50,
                        verbose_name="Voorkeurskanaal",
                    ),
                ),
                (
                    "voorkeurstaal",
                    models.CharField(
                        blank=True,
                        help_text="Taal waarin de partij bij voorkeur contact heeft met de gemeente.",
                        max_length=3,
                        verbose_name="Voorkeurstaal",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Geeft aan of de contactgegevens van de partij nog gebruikt morgen worden om contact op te nemen. Gegevens van niet-actieve partijen mogen hiervoor niet worden gebruikt.",
                        verbose_name="Indicatie actief",
                    ),
                ),
                (
                    "correspondentieadres_nummeraanduiding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                        unique=True,
                    ),
                ),
                (
                    "correspondentieadres_adresregel1",
                    models.CharField(
                        blank=True,
                        help_text="Eerste deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 1",
                    ),
                ),
                (
                    "correspondentieadres_adresregel2",
                    models.CharField(
                        blank=True,
                        help_text="Tweede deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 2",
                    ),
                ),
                (
                    "correspondentieadres_adresregel3",
                    models.CharField(
                        blank=True,
                        help_text="Derde van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 3",
                    ),
                ),
                (
                    "correspondentieadres_land",
                    models.CharField(
                        blank=True,
                        help_text="Een code, opgenomen in Tabel 34, Landentabel, die het land (buiten Nederland) aangeeft alwaar de ingeschrevene verblijft. ",
                        max_length=50,
                        verbose_name="Land",
                    ),
                ),
                (
                    "bezoekadres_nummeraanduiding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                        unique=True,
                    ),
                ),
                (
                    "bezoekadres_adresregel1",
                    models.CharField(
                        blank=True,
                        help_text="Eerste deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 1",
                    ),
                ),
                (
                    "bezoekadres_adresregel2",
                    models.CharField(
                        blank=True,
                        help_text="Tweede deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 2",
                    ),
                ),
                (
                    "bezoekadres_adresregel3",
                    models.CharField(
                        blank=True,
                        help_text="Derde deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 3",
                    ),
                ),
                (
                    "bezoekadres_land",
                    models.CharField(
                        blank=True,
                        help_text="Een code, opgenomen in Tabel 34, Landentabel, die het land (buiten Nederland) aangeeft alwaar de ingeschrevene verblijft.",
                        max_length=50,
                        verbose_name="Land",
                    ),
                ),
            ],
            options={
                "verbose_name": "partij",
                "verbose_name_plural": "partijen",
            },
        ),
        migrations.CreateModel(
            name="Persoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contactnaam_voorletters",
                    models.CharField(
                        help_text="Een afkorting van de voornamen. Meestal de beginletter, maar in sommige gevallen de beginletter gecombineerd met de tweede letter van een voornaam.",
                        max_length=6,
                        verbose_name="Voorletters",
                    ),
                ),
                (
                    "contactnaam_voornaam",
                    models.CharField(
                        blank=True,
                        help_text="De voornaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=200,
                        verbose_name="Voornaam",
                    ),
                ),
                (
                    "contactnaam_voorvoegsel_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Een eventueel voorvoegsel dat hoort bij de achternaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=10,
                        verbose_name="Voorvoegsel achternaam",
                    ),
                ),
                (
                    "contactnaam_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Een achternaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=200,
                        verbose_name="Achternaam",
                    ),
                ),
                (
                    "partij",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persoon",
                        to="klantinteracties.partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persoon",
                "verbose_name_plural": "Personen",
            },
        ),
        migrations.CreateModel(
            name="Organisatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        blank=True,
                        help_text="Naam van de organisatie.",
                        max_length=200,
                        verbose_name="Naam",
                    ),
                ),
                (
                    "partij",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisatie",
                        to="klantinteracties.partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisatie",
                "verbose_name_plural": "Organisaties",
            },
        ),
        migrations.CreateModel(
            name="Contactpersoon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contactnaam_voorletters",
                    models.CharField(
                        help_text="Een afkorting van de voornamen. Meestal de beginletter, maar in sommige gevallen de beginletter gecombineerd met de tweede letter van een voornaam.",
                        max_length=6,
                        verbose_name="Voorletters",
                    ),
                ),
                (
                    "contactnaam_voornaam",
                    models.CharField(
                        blank=True,
                        help_text="De voornaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=200,
                        verbose_name="Voornaam",
                    ),
                ),
                (
                    "contactnaam_voorvoegsel_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Een eventueel voorvoegsel dat hoort bij de achternaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=10,
                        verbose_name="Voorvoegsel achternaam",
                    ),
                ),
                (
                    "contactnaam_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Een achternaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=200,
                        verbose_name="Achternaam",
                    ),
                ),
                (
                    "partij",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persoon",
                        to="klantinteracties.partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persoon",
                "verbose_name_plural": "Personen",
            },
        ),
    ]
