# Generated by Django 3.2.18 on 2023-10-19 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="identificator_object_id",
            new_name="objectidentificator_object_id",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="identificator_objecttype",
            new_name="objectidentificator_objecttype",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="identificator_register",
            new_name="objectidentificator_register",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="identificator_soort_object_id",
            new_name="objectidentificator_soort_object_id",
        ),
        migrations.CreateModel(
            name="Onderwerpobject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objectidentificator_objecttype",
                    models.CharField(
                        help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                        max_length=200,
                        verbose_name="objecttype",
                    ),
                ),
                (
                    "objectidentificator_soort_object_id",
                    models.CharField(
                        help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                        max_length=200,
                        verbose_name="soort object id",
                    ),
                ),
                (
                    "objectidentificator_object_id",
                    models.CharField(
                        help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                        max_length=200,
                        verbose_name="object id",
                    ),
                ),
                (
                    "objectidentificator_register",
                    models.CharField(
                        help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                        max_length=200,
                        verbose_name="register",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van het onderwerpdeel.",
                        unique=True,
                    ),
                ),
                (
                    "klantcontact",
                    models.ForeignKey(
                        help_text="'Klantcontact' ging over 'Onderwerpobject'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.klantcontact",
                        verbose_name="klantcontact",
                    ),
                ),
                (
                    "was_klantcontact",
                    models.ForeignKey(
                        help_text="'Onderwerpobject' was 'Klantcontact'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="was_onderwerpobject",
                        to="klantinteracties.klantcontact",
                        verbose_name="was klantcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "onderwerpobject",
                "verbose_name_plural": "onderwerpobjecten",
            },
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objectidentificator_objecttype",
                    models.CharField(
                        help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                        max_length=200,
                        verbose_name="objecttype",
                    ),
                ),
                (
                    "objectidentificator_soort_object_id",
                    models.CharField(
                        help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                        max_length=200,
                        verbose_name="soort object id",
                    ),
                ),
                (
                    "objectidentificator_object_id",
                    models.CharField(
                        help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                        max_length=200,
                        verbose_name="object id",
                    ),
                ),
                (
                    "objectidentificator_register",
                    models.CharField(
                        help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                        max_length=200,
                        verbose_name="register",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van het inhoudsdeel.",
                        unique=True,
                    ),
                ),
                (
                    "klantcontact",
                    models.ForeignKey(
                        help_text="'Klantcontact' omvatte 'Bijlage'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.klantcontact",
                        verbose_name="klantcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "bijlage",
                "verbose_name_plural": "bijlagen",
            },
        ),
    ]
