# Generated by Django 3.2.18 on 2023-10-10 17:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Klantcontact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de betrokkene bij klantcontact.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        help_text="Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om het specifieke klantcontact aan te duiden.",
                        max_length=10,
                        validators=[django.core.validators.validate_integer],
                        verbose_name="Nummer",
                    ),
                ),
                (
                    "kanaal",
                    models.CharField(
                        help_text="Communicatiekanaal dat bij het klantcontact werd gebruikt.",
                        max_length=50,
                        verbose_name="Kanaal",
                    ),
                ),
                (
                    "onderwerp",
                    models.CharField(
                        help_text="Datgene waarover het klantcontact ging.",
                        max_length=200,
                        verbose_name="Onderwerp",
                    ),
                ),
                (
                    "inhoud",
                    models.CharField(
                        blank=True,
                        help_text="Informatie die tijdens het klantcontact werd overgebracht of uitgewisseld, voor zover die voor betrokkenen of actoren relevant is.",
                        max_length=1000,
                        verbose_name="Inhoud",
                    ),
                ),
                (
                    "initiator",
                    models.CharField(
                        choices=[
                            ("gemeente", "Gemeente"),
                            ("klant", "Klant"),
                            ("vertegenwoordiger", "Vertegenwoordiger"),
                        ],
                        help_text="Degene die het klantcontact initieerde.",
                        max_length=17,
                        verbose_name="Initiator",
                    ),
                ),
                (
                    "indicatie_contact_gelukt",
                    models.BooleanField(
                        help_text="Geeft, indien bekend, aan of de poging contact tussen de gemeente en inwoner(s) of organisatie(s) tot stand te brengen succesvol was.",
                        null=True,
                        verbose_name="Indicatie contact gelukt",
                    ),
                ),
                (
                    "taal",
                    models.CharField(
                        help_text="Taal die bij het klantcontact werd gesproken of geschreven.",
                        max_length=255,
                        verbose_name="Taal",
                    ),
                ),
                (
                    "vertrouwelijk",
                    models.BooleanField(
                        help_text="Geeft aan of onderwerp, inhoud en kenmerken van het klantcontact vertrouwelijk moeten worden behandeld.",
                        verbose_name="Vertrouwelijk",
                    ),
                ),
                (
                    "plaatsgevonden_op",
                    models.DateTimeField(
                        help_text="Datum en tijdstip waarop het klantontact plaatsvond. Als het klantcontact een gesprek betrof, is dit het moment waarop het gesprek begon. Als het klantcontact verzending of ontvangst van informatie betrof, is dit bij benadering het moment waarop informatie door gemeente verzonden of ontvangen werd.",
                        verbose_name="Plaatsgevonden op",
                    ),
                ),
            ],
            options={
                "verbose_name": "klantcontact",
                "verbose_name_plural": "klantcontacten",
            },
        ),
    ]
