# Generated by Django 3.2.18 on 2023-10-19 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0002_auto_20231019_1441"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartijIdentificator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de partij-identificator.",
                        unique=True,
                    ),
                ),
                (
                    "andere_partij_identificator",
                    models.CharField(
                        blank=True,
                        help_text="Vrij tekstveld om de verwijzing naar een niet-voorgedefinieerd objecttype, soort objectID of Register vast te leggen. ",
                        max_length=200,
                        verbose_name="andere partij indetificator",
                    ),
                ),
                (
                    "partij_identificator_objecttype",
                    models.CharField(
                        help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                        max_length=200,
                        verbose_name="objecttype",
                    ),
                ),
                (
                    "partij_identificator_soort_object_id",
                    models.CharField(
                        help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                        max_length=200,
                        verbose_name="soort object id",
                    ),
                ),
                (
                    "partij_identificator_object_id",
                    models.CharField(
                        help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                        max_length=200,
                        verbose_name="object id",
                    ),
                ),
                (
                    "partij_identificator_register",
                    models.CharField(
                        help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                        max_length=200,
                        verbose_name="register",
                    ),
                ),
                (
                    "partij",
                    models.ForeignKey(
                        help_text="'Partij' had 'PartijIdentificator'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.partij",
                        verbose_name="partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "partij identificator",
                "verbose_name_plural": "partij identificatoren",
            },
        ),
    ]
