# Generated by Django 3.2.18 on 2023-10-11 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0002_klantcontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Betrokkene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de betrokkene bij klantcontact.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("vertegenwoordiger", "Vertegenwoordiger"),
                            ("klant", "Klant"),
                        ],
                        help_text="Rol die de betrokkene bij klantcontact tijdens dat contact vervulde.",
                        max_length=17,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "organisatienaam",
                    models.CharField(
                        blank=True,
                        help_text="Naam van de organisatie waarmee de betrokkene bij klantcontact een relatie had.",
                        max_length=200,
                        verbose_name="Organisatienaam",
                    ),
                ),
                (
                    "contactnaam_voorletters",
                    models.CharField(
                        help_text="Een afkorting van de voornamen. Meestal de beginletter, maar in sommige gevallen de beginletter gecombineerd met de tweede letter van een voornaam.",
                        max_length=6,
                        verbose_name="Voorletters",
                    ),
                ),
                (
                    "contactnaam_voornaam",
                    models.CharField(
                        blank=True,
                        help_text="De voornaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=200,
                        verbose_name="Voornaam",
                    ),
                ),
                (
                    "contactnaam_voorvoegsel_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Een eventueel voorvoegsel dat hoort bij de achternaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=10,
                        verbose_name="Voorvoegsel achternaam",
                    ),
                ),
                (
                    "contactnaam_achternaam",
                    models.CharField(
                        blank=True,
                        help_text="Een achternaam die de persoon wil gebruiken tijdens communicatie met de gemeente.",
                        max_length=200,
                        verbose_name="Achternaam",
                    ),
                ),
                (
                    "correspondentieadres_nummeraanduiding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                        unique=True,
                    ),
                ),
                (
                    "correspondentieadres_adresregel1",
                    models.CharField(
                        blank=True,
                        help_text="Eerste deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 1",
                    ),
                ),
                (
                    "correspondentieadres_adresregel2",
                    models.CharField(
                        blank=True,
                        help_text="Tweede deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 2",
                    ),
                ),
                (
                    "correspondentieadres_adresregel3",
                    models.CharField(
                        blank=True,
                        help_text="Derde van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 3",
                    ),
                ),
                (
                    "correspondentieadres_land",
                    models.CharField(
                        blank=True,
                        help_text="Een code, opgenomen in Tabel 34, Landentabel, die het land (buiten Nederland) aangeeft alwaar de ingeschrevene verblijft. ",
                        max_length=50,
                        verbose_name="Land",
                    ),
                ),
                (
                    "bezoekadres_nummeraanduiding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                        unique=True,
                    ),
                ),
                (
                    "bezoekadres_adresregel1",
                    models.CharField(
                        blank=True,
                        help_text="Eerste deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 1",
                    ),
                ),
                (
                    "bezoekadres_adresregel2",
                    models.CharField(
                        blank=True,
                        help_text="Tweede deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 2",
                    ),
                ),
                (
                    "bezoekadres_adresregel3",
                    models.CharField(
                        blank=True,
                        help_text="Derde deel van het adres dat niet voorkomt in de Basisregistratie Adressen en Gebouwen.",
                        max_length=80,
                        verbose_name="Adresregel 3",
                    ),
                ),
                (
                    "bezoekadres_land",
                    models.CharField(
                        blank=True,
                        help_text="Een code, opgenomen in Tabel 34, Landentabel, die het land (buiten Nederland) aangeeft alwaar de ingeschrevene verblijft.",
                        max_length=50,
                        verbose_name="Land",
                    ),
                ),
                (
                    "klantcontact",
                    models.ForeignKey(
                        help_text="'Klantcontact' had 'Betrokkene bij klantcontact'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betrokkene",
                        to="klantinteracties.klantcontact",
                        verbose_name="Klantcontact",
                    ),
                ),
                (
                    "partij",
                    models.ForeignKey(
                        help_text="'Betrokkene bij klantcontact' was 'Partij'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betrokkene",
                        to="klantinteracties.partij",
                        verbose_name="Partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "betrokkene bij klantcontact",
            },
        ),
    ]
