# Generated by Django 3.2.18 on 2023-10-11 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0003_betrokkene"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitaalAdres",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van het digitaal adres.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "soort_digitaal_adres",
                    models.CharField(
                        help_text="Typering van het digitale adres die aangeeft via welk(e) kanaal of kanalen met dit adres contact kan worden opgenomen.",
                        max_length=254,
                        verbose_name="Soort digitaal adres",
                    ),
                ),
                (
                    "adres",
                    models.CharField(
                        help_text="Digitaal adres waarmee een persoon of organisatie bereikt kan worden.",
                        max_length=80,
                        verbose_name="Adres",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        help_text="Omschrijving van het digitaal adres.",
                        max_length=40,
                        verbose_name="Omschrijving",
                    ),
                ),
            ],
            options={
                "verbose_name": "digitaal adres",
            },
        ),
        migrations.AddField(
            model_name="betrokkene",
            name="digitaal_adres",
            field=models.ForeignKey(
                help_text="'Digitaal Adres' had 'Betrokkene bij klantcontact'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partijen",
                to="klantinteracties.digitaaladres",
                verbose_name="Digitaal adres",
            ),
        ),
        migrations.AddField(
            model_name="partij",
            name="digitaal_adres",
            field=models.ForeignKey(
                help_text="'Digitaal Adres' was 'Partij'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="digitale_adressen",
                to="klantinteracties.digitaaladres",
                verbose_name="Digitaal adres",
            ),
        ),
    ]
