# Generated by Django 3.2.18 on 2023-11-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0003_partijidentificator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betrokkene",
            name="digitaal_adres",
        ),
        migrations.AddField(
            model_name="digitaaladres",
            name="betrokkene",
            field=models.ForeignKey(
                help_text="'Digitaal Adres' had 'Betrokkene bij klantcontact'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.betrokkene",
                verbose_name="betrokkene",
            ),
        ),
        migrations.AlterField(
            model_name="medewerker",
            name="actor",
            field=models.ForeignKey(
                help_text="'GeautomatiseerdeActor' was 'Actor'",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medewerker",
                to="klantinteracties.actor",
                unique=True,
                verbose_name="actor",
            ),
        ),
    ]
