# Generated by Django 3.2.18 on 2023-11-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0003_partijidentificator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="betrokkene",
            options={
                "verbose_name": "betrokkene bij klantcontact",
                "verbose_name_plural": "betrokkenen bij klantcontact",
            },
        ),
        migrations.AlterField(
            model_name="actor",
            name="objectidentificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                max_length=200,
                verbose_name="object ID",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="objectidentificator_objecttype",
            field=models.CharField(
                blank=True,
                help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                max_length=200,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="objectidentificator_register",
            field=models.CharField(
                blank=True,
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="register",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="objectidentificator_soort_object_id",
            field=models.CharField(
                blank=True,
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                max_length=200,
                verbose_name="soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=255,
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="contactnaam_voorletters",
            field=models.CharField(
                blank=True,
                help_text="Een afkorting van de voornamen. Meestal de beginletter, maar in sommige gevallen de beginletter gecombineerd met de tweede letter van een voornaam.",
                max_length=10,
                verbose_name="voorletters",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="digitaal_adres",
            field=models.ForeignKey(
                blank=True,
                help_text="'Digitaal Adres' had 'Betrokkene bij klantcontact'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.digitaaladres",
                verbose_name="digitaal adres",
            ),
        ),
        migrations.AlterField(
            model_name="bijlage",
            name="objectidentificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                max_length=200,
                verbose_name="object ID",
            ),
        ),
        migrations.AlterField(
            model_name="bijlage",
            name="objectidentificator_objecttype",
            field=models.CharField(
                blank=True,
                help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                max_length=200,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="bijlage",
            name="objectidentificator_register",
            field=models.CharField(
                blank=True,
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="register",
            ),
        ),
        migrations.AlterField(
            model_name="bijlage",
            name="objectidentificator_soort_object_id",
            field=models.CharField(
                blank=True,
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                max_length=200,
                verbose_name="soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="contactpersoon",
            name="contactnaam_voorletters",
            field=models.CharField(
                blank=True,
                help_text="Een afkorting van de voornamen. Meestal de beginletter, maar in sommige gevallen de beginletter gecombineerd met de tweede letter van een voornaam.",
                max_length=10,
                verbose_name="voorletters",
            ),
        ),
        migrations.AlterField(
            model_name="internetaak",
            name="status",
            field=models.CharField(
                choices=[
                    ("te_verwerken", "Het verzoek is afgehandeld."),
                    ("verwerkt", "Het verzoek ID buiten behandeling gesteld."),
                ],
                help_text="Aanduiding van de vordering bij afhandeling van de interne taak.",
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="internetaak",
            name="toelichting",
            field=models.TextField(
                blank=True,
                help_text="Toelichting die, aanvullend bij de inhoud van het klantcontact dat aanleiding gaf tot de taak en de gevraagde handeling, bijdraagt aan het kunnen afhandelen van de taak.",
                max_length=400,
                verbose_name="toelichting",
            ),
        ),
        migrations.AlterField(
            model_name="klantcontact",
            name="taal",
            field=models.CharField(
                help_text="Taal, in ISO 639-2/B formaat, waarin de partij bij voorkeur contact heeft met de gemeente. Voorbeeld: nld. Zie: https://www.iso.org/standard/4767.html",
                max_length=3,
                verbose_name="taal",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="objectidentificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                max_length=200,
                verbose_name="object ID",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="objectidentificator_objecttype",
            field=models.CharField(
                blank=True,
                help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                max_length=200,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="objectidentificator_register",
            field=models.CharField(
                blank=True,
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="register",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="objectidentificator_soort_object_id",
            field=models.CharField(
                blank=True,
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                max_length=200,
                verbose_name="soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="was_klantcontact",
            field=models.ForeignKey(
                blank=True,
                help_text="'Onderwerpobject' was 'Klantcontact'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="was_onderwerpobject",
                to="klantinteracties.klantcontact",
                verbose_name="was klantcontact",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="betrokkene",
            field=models.ForeignKey(
                blank=True,
                help_text="'Betrokkene bij klantcontact' was 'Partij'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.betrokkene",
                verbose_name="betrokkene",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=255,
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="digitaal_adres",
            field=models.ForeignKey(
                blank=True,
                help_text="'Digitaal Adres' was 'Partij'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.digitaaladres",
                verbose_name="digitaal adres",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="voorkeurs_digitaal_adres",
            field=models.ForeignKey(
                blank=True,
                help_text="'Partij' gaf voorkeur aan voor contact via 'Digitaal adres'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voorkeurs_partij",
                to="klantinteracties.digitaaladres",
                verbose_name="voorkeurs digitaal adres",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                max_length=200,
                verbose_name="object ID",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_objecttype",
            field=models.CharField(
                blank=True,
                help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                max_length=200,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_register",
            field=models.CharField(
                blank=True,
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="register",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_soort_object_id",
            field=models.CharField(
                blank=True,
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                max_length=200,
                verbose_name="soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="contactnaam_voorletters",
            field=models.CharField(
                blank=True,
                help_text="Een afkorting van de voornamen. Meestal de beginletter, maar in sommige gevallen de beginletter gecombineerd met de tweede letter van een voornaam.",
                max_length=10,
                verbose_name="voorletters",
            ),
        ),
    ]
