# Generated by Django 3.2.18 on 2023-10-13 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0004_digitaaladres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "actoridentifcator_objecttype",
                    models.CharField(
                        help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                        max_length=200,
                        verbose_name="Objecttype",
                    ),
                ),
                (
                    "actoridentifcator_soort_object_id",
                    models.CharField(
                        help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                        max_length=200,
                        verbose_name="Soort Object ID",
                    ),
                ),
                (
                    "actoridentifcator_object_id",
                    models.CharField(
                        help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                        max_length=200,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "actoridentifcator_register",
                    models.CharField(
                        help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                        max_length=200,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de actor.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van de actor.",
                        max_length=200,
                        verbose_name="Naam",
                    ),
                ),
                (
                    "soort_actor",
                    models.CharField(
                        choices=[
                            ("medewerker", "Medewerker"),
                            ("geautomatiseerde_actor", "Geautomatiseerde actor"),
                            ("organisatorische_eenheid", "Organisatorische eenheid"),
                        ],
                        help_text="Geeft aan van welke specifieke soort actor sprake is.",
                        max_length=24,
                        verbose_name="Soort actor",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Geeft aan of aan de actor nog betrokken mag worden bij nieuwe klantcontacten. Voor niet-actieve is dit niet toegestaan.",
                        verbose_name="Indicatie actief",
                    ),
                ),
            ],
            options={
                "verbose_name": "actor",
                "verbose_name_plural": "actoren",
            },
        ),
        migrations.AddField(
            model_name="klantcontact",
            name="klantcontact",
            field=models.ForeignKey(
                blank=True,
                help_text="De persoon of organisatie die betrokken was bij een klantcontact.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="klantcontacten",
                to="klantinteracties.klantcontact",
                verbose_name="Klant contact",
            ),
        ),
        migrations.CreateModel(
            name="OrganisatorischeEenheid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Omschrijving van de geautomatiseerde actor.",
                        max_length=200,
                        verbose_name="Omschrijving",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Elektronisch postadres waaronder de MEDEWERKER in de regel bereikbaar is.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "faxnummer",
                    models.CharField(
                        help_text="Faxnummer waaronder de organisatorische eenheid in de regel bereikbaar is.",
                        max_length=20,
                        verbose_name="Faxnummer",
                    ),
                ),
                (
                    "telefoonnummer",
                    models.CharField(
                        help_text="Telefoonnummer waaronder de MEDEWERKER in de regel bereikbaar is.",
                        max_length=20,
                        verbose_name="Telefoonnummer",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="'GeautomatiseerdeActor' was 'Actor'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisatorische_eenheid",
                        to="klantinteracties.actor",
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisatorische eenheid",
            },
        ),
        migrations.CreateModel(
            name="Medewerker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "functie",
                    models.CharField(
                        help_text="Functie van de geautomatiseerde actor of beschrijving van de werkzaamheden die deze uitvoert.",
                        max_length=40,
                        verbose_name="Functie",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Elektronisch postadres waaronder de MEDEWERKER in de regel bereikbaar is.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "telefoonnummer",
                    models.CharField(
                        help_text="Telefoonnummer waaronder de MEDEWERKER in de regel bereikbaar is.",
                        max_length=20,
                        verbose_name="Telefoonnummer",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="'GeautomatiseerdeActor' was 'Actor'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medewerker",
                        to="klantinteracties.actor",
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "medewerker",
                "verbose_name_plural": "Mederwerkers",
            },
        ),
        migrations.CreateModel(
            name="GeautomatiseerdeActor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "functie",
                    models.CharField(
                        help_text="Functie van de geautomatiseerde actor of beschrijving van de werkzaamheden die deze uitvoert.",
                        max_length=40,
                        verbose_name="Functie",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Omschrijving van de geautomatiseerde actor.",
                        max_length=200,
                        verbose_name="Omschrijving",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="'GeautomatiseerdeActor' was 'Actor'",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geautomatiseerde_actor",
                        to="klantinteracties.actor",
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "geautomatiseerde actor",
                "verbose_name_plural": "geautomatiseerde actoren",
            },
        ),
        migrations.AddField(
            model_name="klantcontact",
            name="actoren",
            field=models.ManyToManyField(
                help_text="De actoren die tijdens het klantcontant contact had met klanten of hun vertegenwoordigers.",
                related_name="klantcontacten",
                to="klantinteracties.Actor",
                verbose_name="Actoren",
            ),
        ),
    ]
