# Generated by Django 3.2.18 on 2023-10-12 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0005_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterneTaak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de interne taak.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        help_text="Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke interne taak aan te duiden.",
                        max_length=10,
                        validators=[django.core.validators.validate_integer],
                        verbose_name="Nummer",
                    ),
                ),
                (
                    "gevraagde_handeling",
                    models.CharField(
                        help_text="Handeling die moet worden uitgevoerd om de taak af te ronden.",
                        max_length=200,
                        verbose_name="Gevraagde handeling",
                    ),
                ),
                (
                    "toelichting",
                    models.CharField(
                        help_text="Toelichting die, aanvullend bij de inhoud van het klantcontact dat aanleiding gaf tot de taak en de gevraagde handeling, bijdraagt aan het kunnen afhandelen van de taak.",
                        max_length=400,
                        verbose_name="Toelichting",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("te_verwerken", "Het verzoek is afgehandeld."),
                            ("verwerkt", "Het verzoek id buiten behandeling gesteld."),
                        ],
                        help_text="Aanduiding van de vordering bij afhandeling van de interne taak.",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "toegewezen_op",
                    models.DateTimeField(
                        help_text="Datum en tijdstip waarop de interne taak aan een actor werd toegewezen.",
                        verbose_name="Toegewezen op",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="De actor aan wie de interne taak werd toegewezen.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interne_taak",
                        to="klantinteracties.actor",
                        verbose_name="Actor",
                    ),
                ),
                (
                    "klantcontact",
                    models.ForeignKey(
                        help_text="Het klantcontact dat aanleiding gaf tot het ontstaan van een interne taak.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interne_taak",
                        to="klantinteracties.klantcontact",
                        verbose_name="Klantcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "interne taak",
                "verbose_name_plural": "interne taken",
            },
        ),
    ]
