# Generated by Django 3.2.18 on 2023-11-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0005_auto_20231110_0735"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partij",
            name="betrokkene",
        ),
        migrations.RemoveField(
            model_name="partij",
            name="digitaal_adres",
        ),
        migrations.AddField(
            model_name="betrokkene",
            name="partij",
            field=models.ForeignKey(
                blank=True,
                help_text="'Betrokkene bij klantcontact' was 'Partij'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.partij",
                verbose_name="partij",
            ),
        ),
        migrations.AddField(
            model_name="digitaaladres",
            name="partij",
            field=models.ForeignKey(
                blank=True,
                help_text="'Digitaal Adres' was 'Partij'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.partij",
                verbose_name="partij",
            ),
        ),
        migrations.AlterField(
            model_name="internetaak",
            name="toelichting",
            field=models.TextField(
                blank=True,
                help_text="Toelichting die, aanvullend bij de inhoud van het klantcontact dat aanleiding gaf tot de taak en de gevraagde handeling, bijdraagt aan het kunnen afhandelen van de taak.",
                max_length=1000,
                verbose_name="toelichting",
            ),
        ),
    ]
