# Generated by Django 3.2.18 on 2023-11-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0006_auto_20231124_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geautomatiseerdeactor",
            name="actor",
            field=models.OneToOneField(
                help_text="'GeautomatiseerdeActor' was 'Actor'",
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.actor",
                verbose_name="Actor",
            ),
        ),
        migrations.AlterField(
            model_name="medewerker",
            name="actor",
            field=models.OneToOneField(
                help_text="'GeautomatiseerdeActor' was 'Actor'",
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.actor",
                verbose_name="actor",
            ),
        ),
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="actor",
            field=models.OneToOneField(
                help_text="'GeautomatiseerdeActor' was 'Actor'",
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.actor",
                verbose_name="actor",
            ),
        ),
    ]
