# Generated by Django 3.2.18 on 2023-11-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0007_auto_20231128_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpersoon",
            name="partij",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.partij",
                verbose_name="partij",
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="partij",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.partij",
                verbose_name="partij",
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="partij",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.partij",
                verbose_name="partij",
            ),
        ),
    ]
