# Generated by Django 3.2.23 on 2024-01-16 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0007_auto_20231201_1601"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetaak",
            name="nummer",
            field=models.CharField(
                blank=True,
                help_text="Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke interne taak aan te duiden.",
                max_length=10,
                unique=True,
                validators=[django.core.validators.validate_integer],
                verbose_name="nummer",
            ),
        ),
        migrations.AlterField(
            model_name="klantcontact",
            name="nummer",
            field=models.CharField(
                blank=True,
                help_text="Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om het specifieke klantcontact aan te duiden.",
                max_length=10,
                unique=True,
                validators=[django.core.validators.validate_integer],
                verbose_name="nummer",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="nummer",
            field=models.CharField(
                blank=True,
                help_text="Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke partij aan te duiden.",
                max_length=10,
                unique=True,
                validators=[django.core.validators.validate_integer],
                verbose_name="nummer",
            ),
        ),
    ]
