# Generated by Django 3.2.23 on 2024-02-07 14:16

from django.db import migrations, models
import django.db.models.deletion
import openklant.utils.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0009_categorie_categorierelatie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="klantcontact",
            name="actoren",
        ),
        migrations.RemoveField(
            model_name="partij",
            name="vertegenwoordigde",
        ),
        migrations.AlterField(
            model_name="medewerker",
            name="telefoonnummer",
            field=models.CharField(
                help_text="Telefoonnummer waaronder de MEDEWERKER in de regel bereikbaar is.",
                max_length=20,
                validators=[openklant.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
        ),
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="telefoonnummer",
            field=models.CharField(
                help_text="Telefoonnummer waaronder de MEDEWERKER in de regel bereikbaar is.",
                max_length=20,
                validators=[openklant.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
        ),
        migrations.CreateModel(
            name="Vertegenwoordigden",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de vertegenwoordigden.",
                        unique=True,
                    ),
                ),
                (
                    "vertegenwoordigde_partij",
                    models.ForeignKey(
                        help_text="'Partij' vertegenwoordigd wordt door een andere 'Partij'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertegenwoordigde",
                        to="klantinteracties.partij",
                        verbose_name="vertegenwoordigde partij",
                    ),
                ),
                (
                    "vertegenwoordigende_partij",
                    models.ForeignKey(
                        help_text="'Partij' die een andere 'Partij' vertegenwoordigde.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertegenwoordigende",
                        to="klantinteracties.partij",
                        verbose_name="vertegenwoordigende partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "vertegenwoordigde",
                "verbose_name_plural": "vertegenwoordigden",
                "unique_together": {
                    ("vertegenwoordigende_partij", "vertegenwoordigde_partij")
                },
            },
        ),
        migrations.CreateModel(
            name="ActorKlantcontact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de actor klantcontact.",
                        unique=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="De gekoppelde 'Actor'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.actor",
                        verbose_name="actor",
                    ),
                ),
                (
                    "klantcontact",
                    models.ForeignKey(
                        help_text="De gekoppelde 'Klantcontact'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.klantcontact",
                        verbose_name="klantcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "actor klantcontact",
                "verbose_name_plural": "actor klantcontacten",
                "unique_together": {("actor", "klantcontact")},
            },
        ),
    ]
