# Generated by Django 3.2.23 on 2024-01-31 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import openklant.utils.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0010_auto_20240207_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partij",
            name="voorkeurs_digitaal_adres",
            field=models.ForeignKey(
                blank=True,
                help_text="'Partij' gaf voorkeur aan voor contact via 'Digitaal adres'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voorkeurs_partij",
                to="klantinteracties.digitaaladres",
                verbose_name="voorkeurs digitaal adres",
            ),
        ),
        migrations.CreateModel(
            name="Rekeningnummer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van de interne taak.",
                        unique=True,
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        help_text="Het internationaal bankrekeningnummer, zoals dat door een bankinstelling als identificator aan een overeenkomst tussen de bank en een of meer subjecten wordt toegekend, op basis waarvan het SUBJECT in de regel internationaal financieel communiceert.",
                        max_length=34,
                        validators=[
                            openklant.utils.validators.CustomRegexValidator(
                                message="Ongeldige IBAN",
                                regex="^[A-Za-z]{2}[0-9]{2}[A-Za-z0-9]{1,30}$",
                            )
                        ],
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True,
                        help_text="De unieke code van de bankinstelling waar het SUBJECT het bankrekeningnummer heeft waarmee het subject in de regel internationaal financieel communiceert.",
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            openklant.utils.validators.CustomRegexValidator(
                                message="Geen spaties toegestaan", regex="^[^\\S]+$"
                            ),
                        ],
                        verbose_name="BIC",
                    ),
                ),
                (
                    "partij",
                    models.ForeignKey(
                        blank=True,
                        help_text="'Rekeninnummer' van 'Partij'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.partij",
                        verbose_name="partij",
                    ),
                ),
            ],
            options={
                "verbose_name": "rekeningnummer",
                "verbose_name_plural": "rekeningnummers",
            },
        ),
        migrations.AddField(
            model_name="partij",
            name="voorkeurs_rekeningnummer",
            field=models.ForeignKey(
                blank=True,
                help_text="'Partij' gaf voorkeur voor 'rekeningnummer'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voorkeurs_rekeningnummer",
                to="klantinteracties.rekeningnummer",
                verbose_name="voorkeurs rekeningnummer",
            ),
        ),
    ]
