# Generated by Django 3.2.23 on 2024-02-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0011_auto_20240209_0928'),
        ('klantinteracties', '0011_rekeningnummer'),
    ]

    operations = [
    ]
