# Generated by Django 4.2.11 on 2024-03-15 13:05

import django.core.validators
from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0012_merge_0011_auto_20240209_0928_0011_rekeningnummer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="faxnummer",
            field=models.CharField(
                blank=True,
                help_text="Faxnummer waaronder de organisatorische eenheid in de regel bereikbaar is.",
                max_length=20,
                verbose_name="faxnummer",
            ),
        ),
        migrations.AlterField(
            model_name="organisatorischeeenheid",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                help_text="Telefoonnummer waaronder de MEDEWERKER in de regel bereikbaar is.",
                max_length=20,
                validators=[openklant.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
        ),
        migrations.AlterField(
            model_name="rekeningnummer",
            name="bic",
            field=models.CharField(
                blank=True,
                help_text="De unieke code van de bankinstelling waar het SUBJECT het bankrekeningnummer heeft waarmee het subject in de regel internationaal financieel communiceert.",
                max_length=11,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    openklant.utils.validators.CustomRegexValidator(
                        message="Geen spaties toegestaan", regex="^[\\S]+$"
                    ),
                ],
                verbose_name="BIC",
            ),
        ),
    ]
