# Generated by Django 4.2.11 on 2024-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0013_alter_organisatorischeeenheid_faxnummer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internetaak",
            name="status",
            field=models.CharField(
                choices=[("te_verwerken", "Te verwerken."), ("verwerkt", "Verwerkt")],
                help_text="Aanduiding van de vordering bij afhandeling van de interne taak.",
                max_length=12,
                verbose_name="status",
            ),
        ),
    ]
