# Generated by Django 4.2.11 on 2024-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0014_alter_internetaak_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetaak",
            name="afgehandeld_op",
            field=models.DateTimeField(
                blank=True,
                help_text="Datum en tijdstip wanneer de interne taak was afgehandeld: EXPERIMENTEEL.",
                null=True,
                verbose_name="afgehandeld op",
            ),
        ),
    ]
