# Generated by Django 4.2.11 on 2024-08-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def sync_actor_and_actoren(apps, schema_editor):
        Internetaak = apps.get_model("klantinteracties", "internetaak")
        for internetaak in Internetaak.objects.all():
            internetaak.actoren.add(internetaak.actor)

    dependencies = [
        ("klantinteracties", "0015_internetaak_afgehandeld_op"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterneActorenThoughModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.actor",
                    ),
                ),
                (
                    "internetaak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.internetaak",
                    ),
                ),
            ],
            options={
                "ordering": ("actor", "order"),
            },
        ),
        migrations.AddField(
            model_name="internetaak",
            name="actoren",
            field=models.ManyToManyField(
                help_text="De actoren aan wie de interne taak werd toegewezen.",
                through="klantinteracties.InterneActorenThoughModel",
                to="klantinteracties.actor",
                verbose_name="actoren",
            ),
        ),
        migrations.RunPython(sync_actor_and_actoren),
        migrations.RemoveField(
            model_name="internetaak",
            name="actor",
        ),
    ]
