# Generated by Django 4.2.11 on 2024-08-15 22:34

from django.db import migrations


class Migration(migrations.Migration):
    def sync_actor_and_actoren(apps, schema_editor):
        Internetaak = apps.get_model("klantinteracties", "internetaak")
        for internetaak in Internetaak.objects.all():
            internetaak.actoren.add(internetaak.actor)

    def reverse_sync_actor_and_actoren(apps, schema_editor):
        Internetaak = apps.get_model("klantinteracties", "internetaak")
        for internetaak in Internetaak.objects.all():
            internetaak.actor = internetaak.actoren.first()
            internetaak.save()

    dependencies = [
        ("klantinteracties", "0016_internetaak_actoren"),
    ]

    operations = [
        migrations.RunPython(
            sync_actor_and_actoren, reverse_code=reverse_sync_actor_and_actoren
        ),
    ]
