# Generated by Django 4.2.11 on 2024-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0018_remove_internetaak_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partij",
            name="indicatie_geheimhouding",
            field=models.BooleanField(
                default=None,
                help_text="Geeft aan of de verstrekker van partijgegevens heeft aangegeven dat deze gegevens als geheim beschouwd moeten worden. Als dit niet aangegeven is dan wordt dit ingevuld als `null`.",
                null=True,
                verbose_name="indicatie geheimhouding",
            ),
        ),
    ]
