# Generated by Django 4.2.15 on 2024-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0019_alter_partij_indicatie_geheimhouding"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitaaladres",
            name="is_standaard_adres",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of dit digitaal adres het standaard adres is voor het `soort_digitaal_adres`",
                verbose_name="Is standaard adres",
            ),
        ),
    ]
