# Generated by Django 4.2.15 on 2024-10-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0020_alter_digitaaladres_soort_digitaal_adres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaaladres",
            name="soort_digitaal_adres",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("telefoonnummer", "Telefoonnummer"),
                    ("overig", "Overig"),
                ],
                help_text="Typering van het digitale adres die aangeeft via welk(e) kanaal of kanalen met dit adres contact kan worden opgenomen.",
                max_length=255,
                verbose_name="soort digitaal adres",
            ),
        ),
    ]
