# Generated by Django 4.2.15 on 2024-10-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0020_alter_digitaaladres_soort_digitaal_adres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaaladres",
            name="betrokkene",
            field=models.ForeignKey(
                blank=True,
                help_text="'Digitaal Adres' had 'Betrokkene bij klantcontact'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.betrokkene",
                verbose_name="betrokkene",
            ),
        ),
    ]
