# Generated by Django 4.2.15 on 2024-10-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0021_alter_digitaaladres_betrokkene"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitaaladres",
            name="is_standaard_adres",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of dit digitaal adres het standaard adres is voor het `soort_digitaal_adres`",
                verbose_name="Is standaard adres",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitaaladres",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_standaard_adres", True)),
                fields=("partij", "soort_digitaal_adres"),
                name="unique_default_per_partij_and_soort",
            ),
        ),
    ]
