# Generated by Django 4.2.15 on 2024-11-08 13:26

from django.db import migrations, models
import django.db.models.deletion
import openklant.components.utils.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0022_digitaaladres_is_standaard_adres_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetrokkeneAdres",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke (technische) identificatiecode van het digitaal adres.",
                        unique=True,
                    ),
                ),
                (
                    "soort_digitaal_adres",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telefoonnummer", "Telefoonnummer"),
                            ("overig", "Overig"),
                        ],
                        help_text="Typering van het digitale adres die aangeeft via welk(e) kanaal of kanalen met dit adres contact kan worden opgenomen.",
                        max_length=255,
                        verbose_name="soort digitaal adres",
                    ),
                ),
                (
                    "adres",
                    models.CharField(
                        help_text="Digitaal adres waarmee een persoon of organisatie bereikt kan worden.",
                        max_length=80,
                        verbose_name="adres",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        help_text="Omschrijving van het digitaal adres.",
                        max_length=40,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "betrokkene",
                    models.ForeignKey(
                        blank=True,
                        help_text="'Digitaal Adres' had 'Betrokkene bij klantcontact'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klantinteracties.betrokkene",
                        verbose_name="betrokkene",
                    ),
                ),
            ],
            options={
                "verbose_name": "betrokkene adres",
            },
            bases=(openklant.components.utils.mixins.APIMixin, models.Model),
        ),
    ]
