# Generated by Django 4.2.15 on 2024-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0022_digitaaladres_is_standaard_adres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaaladres",
            name="omschrijving",
            field=models.CharField(
                blank=True,
                help_text="Omschrijving van het digitaal adres.",
                max_length=40,
                verbose_name="omschrijving",
            ),
        ),
    ]
