# Generated by Django 4.2.15 on 2025-01-09 09:22

import json
import logging
import openklant.utils.validators
from django.core.management import CommandError
from django.db import migrations, models
from django.db.models.functions import Length

logger = logging.getLogger(__name__)


def _log_records(records, model_name):
    logger.info("--- START %s INFO ---", model_name)
    logger.info(
        "Found %s records for %s that have bezoekadres_nummeraanduiding_id "
        "or correspondentieadres_nummeraanduiding_id length > 16 chars",
        records.count(),
        model_name,
    )

    for record in records:
        logger.warning(
            json.dumps(
                {
                    "model_name": model_name,
                    "pk": record.pk,
                    "uuid": str(record.uuid),
                    "bezoekadres_nummeraanduiding_id": record.bezoekadres_nummeraanduiding_id,
                    "correspondentieadres_nummeraanduiding_id": record.correspondentieadres_nummeraanduiding_id,
                }
            )
        )

    logger.info("--- END %s INFO ---", model_name)


def _check_field_length(apps, schema_editor):

    Betrokkene = apps.get_model("klantinteracties", "Betrokkene")
    Partij = apps.get_model("klantinteracties", "Partij")

    betrokkene_queryset = Betrokkene.objects.annotate(
        length1=Length("bezoekadres_nummeraanduiding_id"),
        length2=Length("correspondentieadres_nummeraanduiding_id"),
    ).filter(models.Q(length1__gt=16) | models.Q(length2__gt=16))

    partij_queryset = Partij.objects.annotate(
        length1=Length("bezoekadres_nummeraanduiding_id"),
        length2=Length("correspondentieadres_nummeraanduiding_id"),
    ).filter(models.Q(length1__gt=16) | models.Q(length2__gt=16))

    _log_records(betrokkene_queryset, "Betrokkene")
    _log_records(partij_queryset, "Partij")

    if betrokkene_queryset or partij_queryset:
        raise CommandError(
            "The migration cannot proceed due to data that doesn't comply with the model's requirements."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.RunPython(
            code=_check_field_length,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
    ]
