# Generated by Django 4.2.15 on 2025-01-09 15:19

import logging
import django.core.validators
import openklant.utils.validators
from django.db import migrations, models
import openklant.utils.validators


from openklant.utils.converters import nl_code_to_iso_code_country_converter

logger = logging.getLogger(__name__)


def _update_records(records, class_name):
    logger.info("Start updating records for %s", class_name)
    for record in records:
        updated = False
        if record.bezoekadres_land:
            value = nl_code_to_iso_code_country_converter(record.bezoekadres_land)
            if not value:
                logger.warning(
                    "%s object (pk: %s, uuid: %s) has no match for the nl_code '%s'",
                    class_name,
                    record.pk,
                    record.uuid,
                    record.adres_land,
                )
            record.bezoekadres_land = value
            updated = True
        if record.correspondentieadres_land:
            value = nl_code_to_iso_code_country_converter(
                record.correspondentieadres_land
            )
            if not value:
                logger.warning(
                    "%s object (pk: %s, uuid: %s) has no match for the nl_code '%s'",
                    class_name,
                    record.pk,
                    record.uuid,
                    record.adres_land,
                )
            record.correspondentieadres_land = value
            updated = True
        if updated:
            logger.debug(
                "Object %s pk: %s uuid %s updated",
                class_name,
                record.pk,
                record.uuid,
            )
            record.save()
    logger.info("Records update finished")


def _update_country_code(apps, schema_editor):
    Betrokkene = apps.get_model("klantinteracties", "Betrokkene")
    Partij = apps.get_model("klantinteracties", "Partij")

    _update_records(Betrokkene.objects.all(), "Betrokkene")
    _update_records(Partij.objects.all(), "Partij")


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.RunPython(
            code=_update_country_code,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
    ]
