# Generated by Django 4.2.15 on 2025-01-08 11:12

from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
    ]
