# Generated by Django 4.2.15 on 2025-01-09 09:22

import json
import logging
import openklant.utils.validators
from django.core.management import CommandError
from django.db import migrations, models
from django.db.models.functions import Length

logger = logging.getLogger(__name__)


def _check_nummeraanduiding_length(apps, schema_editor):

    Betrokkene = apps.get_model("klantinteracties", "Betrokkene")
    Partij = apps.get_model("klantinteracties", "Partij")

    betrokkene_queryset = Betrokkene.objects.annotate(
        length1=Length("bezoekadres_nummeraanduiding_id"),
        length2=Length("correspondentieadres_nummeraanduiding_id"),
    ).filter(models.Q(length1__gt=16) | models.Q(length2__gt=16))

    logger.info("--- START Betrokkene INFO ---")
    logger.info(
        "Found %s records for Betrokkene that have bezoekadres_nummeraanduiding_id or correspondentieadres_nummeraanduiding_id length > 16 chars",
        betrokkene_queryset.count(),
    )

    for record in betrokkene_queryset:
        logger.warning(
            json.dumps(
                {
                    "pk": record.pk,
                    "uuid": str(record.uuid),
                    "bezoekadres_nummeraanduiding_id": record.bezoekadres_nummeraanduiding_id,
                    "correspondentieadres_nummeraanduiding_id": record.correspondentieadres_nummeraanduiding_id,
                }
            )
        )

    logger.info("--- END Betrokkene INFO ---")

    partij_queryset = Partij.objects.annotate(
        length1=Length("bezoekadres_nummeraanduiding_id"),
        length2=Length("correspondentieadres_nummeraanduiding_id"),
    ).filter(models.Q(length1__gt=16) | models.Q(length2__gt=16))

    logger.info("--- START Partij INFO ---")
    logger.info(
        "Found %s records for Partij that have bezoekadres_nummeraanduiding_id or correspondentieadres_nummeraanduiding_id length > 16 chars",
        partij_queryset.count(),
    )

    for record in partij_queryset:
        logger.info(
            json.dumps(
                {
                    "pk": record.pk,
                    "uuid": str(record.uuid),
                    "bezoekadres_nummeraanduiding_id": record.bezoekadres_nummeraanduiding_id,
                    "correspondentieadres_nummeraanduiding_id": record.correspondentieadres_nummeraanduiding_id,
                }
            )
        )

    logger.warning("--- END Partij INFO ---")

    if betrokkene_queryset or partij_queryset:
        raise CommandError(
            "The migration cannot proceed due to data that doesn't comply with the model's requirements."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.RunPython(_check_nummeraanduiding_length),
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_nummeraanduiding_id",
            field=models.CharField(
                blank=True,
                help_text="Identificatie van het adres bij de Basisregistratie Adressen en Gebouwen.",
                max_length=16,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Ongeldige nummeraanduiding BAG-ID", regex="^[0-9]{16}$"
                    )
                ],
                verbose_name="nummeraanduiding ID",
            ),
        ),
    ]
