# Generated by Django 4.2.15 on 2025-01-09 15:19

import django.core.validators
from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_land",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-code die het land (buiten Nederland) aangeeft waar de abonnee woont.",
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=2),
                    openklant.utils.validators.validate_country,
                ],
                verbose_name="land",
            ),
        ),
    ]
