# Generated by Django 4.2.15 on 2024-12-23 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_code_objecttype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natuurlijk_persoon", "NatuurlijkPersoon"),
                    ("niet_natuurlijk_persoon", "NietNatuurlijkPersoon"),
                    ("vestiging", "Vestiging"),
                    ("overig", "Overig"),
                ],
                help_text="Type van het object, bijvoorbeeld: 'NATUURLIJK PERSOON'.",
                max_length=200,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_code_register",
            field=models.CharField(
                blank=True,
                choices=[("brp", "BRP"), ("hr", "HR"), ("overig", "Overig")],
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="register",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_code_soort_object_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bsn", "Bsn"),
                    ("vestigingsnummer", "Vestigingsnummer"),
                    ("kvk_nummer", "Kvk Nummer"),
                    ("rsin", "Rsin"),
                    ("overig", "Overig"),
                ],
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Bsn'.",
                max_length=200,
                verbose_name="soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                max_length=200,
                validators=[django.core.validators.validate_integer],
                verbose_name="object ID",
            ),
        ),
    ]
