# Generated by Django 4.2.15 on 2025-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0023_alter_digitaaladres_omschrijving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaaladres",
            name="is_standaard_adres",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of dit digitaal adres het standaard adres is voor het `soortDigitaalAdres`",
                verbose_name="Is standaard adres",
            ),
        ),
    ]
