# Generated by Django 4.2.15 on 2024-11-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0024_migrate_digitaaladres_to_betrokkeneadres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitaaladres",
            name="betrokkene",
        ),
    ]
