# Generated by Django 4.2.15 on 2025-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0024_alter_digitaaladres_is_standaard_adres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_code_objecttype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natuurlijk_persoon", "NatuurlijkPersoon"),
                    ("niet_natuurlijk_persoon", "NietNatuurlijkPersoon"),
                    ("vestiging", "Vestiging"),
                    ("overig", "Overig"),
                ],
                help_text="Type van het object, bijvoorbeeld: 'natuurlijk_persoon'.",
                max_length=200,
                verbose_name="objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_code_register",
            field=models.CharField(
                blank=True,
                choices=[("brp", "BRP"), ("hr", "HR"), ("overig", "Overig")],
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="register",
            ),
        ),
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij_identificator_code_soort_object_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bsn", "Bsn"),
                    ("vestigingsnummer", "Vestigingsnummer"),
                    ("kvk_nummer", "KvkNummer"),
                    ("rsin", "Rsin"),
                    ("overig", "Overig"),
                ],
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'bsn'.",
                max_length=200,
                verbose_name="soort object ID",
            ),
        ),
    ]
