# Generated by Django 4.2.17 on 2025-02-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "klantinteracties",
            "0027_alter_betrokkene_bezoekadres_nummeraanduiding_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partijidentificator",
            name="sub_identificator_van",
            field=models.ForeignKey(
                blank=True,
                help_text="Expresses that one PartijIdentificator is bound to another one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_partij_identificator",
                to="klantinteracties.partijidentificator",
                verbose_name="sub identificator van",
            ),
        ),
    ]
