# Generated by Django 4.2.17 on 2025-02-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "klantinteracties",
            "0027_alter_betrokkene_bezoekadres_nummeraanduiding_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partijidentificator",
            name="sub_identificator_van",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent PartijIdentificator under which this PartijIdentificator is unique (e.g. the parent identificator could specify a KVK number and the child identificator could specify a vestigingsnummer that is unique for the KVK number).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parent_partij_identificator",
                to="klantinteracties.partijidentificator",
                verbose_name="sub identificator van",
            ),
        ),
        migrations.AddConstraint(
            model_name="partijidentificator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_identificator_van__isnull", True)),
                fields=(
                    "partij_identificator_code_objecttype",
                    "partij_identificator_code_soort_object_id",
                    "partij_identificator_object_id",
                    "partij_identificator_code_register",
                ),
                name="non_scoped_identificator_globally_unique",
                violation_error_message="`PartijIdentificator` moet uniek zijn, er bestaat er al een met deze gegevenscombinatie.",
            ),
        ),
        migrations.AddConstraint(
            model_name="partijidentificator",
            constraint=models.UniqueConstraint(
                fields=("partij", "partij_identificator_code_soort_object_id"),
                name="non_scoped_identificator_locally_unique",
                violation_error_message="`CodeSoortObjectId` moet uniek zijn voor de Partij.",
            ),
        ),
        migrations.AddConstraint(
            model_name="partijidentificator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_identificator_van__isnull", False)),
                fields=(
                    "sub_identificator_van",
                    "partij_identificator_code_objecttype",
                    "partij_identificator_code_soort_object_id",
                    "partij_identificator_object_id",
                    "partij_identificator_code_register",
                ),
                name="scoped_identificator_globally_unique",
                violation_error_message="`PartijIdentificator` moet uniek zijn, er bestaat er al een met deze gegevenscombinatie.",
            ),
        ),
    ]
