# Generated by Django 4.2.17 on 2025-02-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "klantinteracties",
            "0027_alter_betrokkene_bezoekadres_nummeraanduiding_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partijidentificator",
            name="sub_identificator_van",
            field=models.ForeignKey(
                blank=True,
                help_text="Expresses that one PartijIdentificator is bound to another one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_partij_identificator",
                to="klantinteracties.partijidentificator",
                verbose_name="sub identificator van",
            ),
        ),
        migrations.AddConstraint(
            model_name="partijidentificator",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("sub_identificator_van", models.F("id")), _negated=True
                ),
                name="check_sub_identificator_van_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="partijidentificator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_identificator_van__isnull", False)),
                fields=(
                    "sub_identificator_van",
                    "partij_identificator_code_objecttype",
                    "partij_identificator_code_soort_object_id",
                    "partij_identificator_object_id",
                    "partij_identificator_code_register",
                ),
                name="scoped_identificator_globally_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="partijidentificator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sub_identificator_van__isnull", True)),
                fields=(
                    "partij_identificator_code_objecttype",
                    "partij_identificator_code_soort_object_id",
                    "partij_identificator_object_id",
                    "partij_identificator_code_register",
                ),
                name="non_scoped_identificator_globally_unique",
            ),
        ),
    ]
