# Generated by Django 4.2.19 on 2025-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0029_betrokkene_bezoekadres_huisnummer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetaak",
            name="new_actoren",
            field=models.ManyToManyField(
                help_text="De actoren aan wie de interne taak werd toegewezen.",
                related_name="temporary_related_name",
                to="klantinteracties.actor",
                verbose_name="actoren",
            ),
        ),
    ]
