# Generated by Django 4.2.19 on 2025-03-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0029_betrokkene_bezoekadres_huisnummer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partijidentificator",
            name="partij",
            field=models.ForeignKey(
                blank=True,
                help_text="'Partij' had 'PartijIdentificator'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klantinteracties.partij",
                verbose_name="partij",
            ),
        ),
    ]
