# Generated by Django 4.2.19 on 2025-03-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0030_partijidentificator_partij_blank_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitaaladres",
            name="referentie",
            field=models.SlugField(
                default="default_refentie_value",
                help_text="Machine-readable tag for digital address.",
                verbose_name="referentie",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="digitaaladres",
            constraint=models.UniqueConstraint(
                condition=models.Q(("partij__isnull", False)),
                fields=("partij", "referentie"),
                name="unique_referentie_per_parij",
            ),
        ),
    ]
