# Generated by Django 4.2.19 on 2025-03-11 20:09

from django.db import migrations, models
from django.db.migrations.state import StateApps


def sync_actoren_fields(apps: StateApps, _):
    InterneTaak = apps.get_model("klantinteracties", "internetaak")
    for internetaak in InterneTaak.objects.all():
        actoren = internetaak.actoren.all()
        internetaak.new_actoren.set(actoren)
        internetaak.save()


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0030_internetaak_new_actoren"),
    ]

    operations = [
        migrations.RunPython(sync_actoren_fields, migrations.RunPython.noop),
    ]
