# Generated by Django 4.2.19 on 2025-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0030_partijidentificator_partij_blank_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitaaladres",
            name="referentie",
            field=models.SlugField(
                blank=True,
                help_text="Machine-leesbare tag voor unieke identificatie van het digitaal adres.",
                verbose_name="referentie",
            ),
        ),
        migrations.AddConstraint(
            model_name="digitaaladres",
            constraint=models.UniqueConstraint(
                condition=models.Q(("referentie__gt", ""), ("partij__isnull", False)),
                fields=("partij", "referentie"),
                name="unique_referentie_per_partij",
            ),
        ),
    ]
