# Generated by Django 4.2.20 on 2025-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0031_digitaaladres_referentie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_code_objecttype",
            field=models.CharField(
                blank=True,
                help_text="Type van het object, bijvoorbeeld: 'zaak'.",
                max_length=200,
                verbose_name="code objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_code_register",
            field=models.CharField(
                blank=True,
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'open-zaak'.",
                max_length=200,
                verbose_name="code register",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_code_soort_object_id",
            field=models.CharField(
                blank=True,
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'uuid'.",
                max_length=200,
                verbose_name="code soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '095be615-a8ad-4c33-8e9c-c7612fbf6c9f'.",
                max_length=200,
                verbose_name="object ID",
            ),
        ),
    ]
