# Generated by Django 4.2.19 on 2025-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0031_auto_20250311_2009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internetaak",
            name="actoren",
        ),
        migrations.AlterField(
            model_name="internetaak",
            name="new_actoren",
            field=models.ManyToManyField(
                help_text="De actoren aan wie de interne taak werd toegewezen.",
                to="klantinteracties.actor",
                verbose_name="actoren",
            ),
        ),
    ]
