# Generated by Django 4.2.20 on 2025-05-09 13:21

from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0032_alter_betrokkene_bezoekadres_postcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
    ]
