# Generated by Django 4.2.20 on 2025-05-13 09:28

from django.db import migrations, models
import openklant.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "klantinteracties",
            "0032_alter_onderwerpobject_onderwerpobjectidentificator_code_objecttype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="betrokkene",
            name="bezoekadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="betrokkene",
            name="correspondentieadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_code_objecttype",
            field=models.CharField(
                blank=True,
                help_text="Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.",
                max_length=200,
                verbose_name="code objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_code_register",
            field=models.CharField(
                blank=True,
                help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.",
                max_length=200,
                verbose_name="code register",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_code_soort_object_id",
            field=models.CharField(
                blank=True,
                help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.",
                max_length=200,
                verbose_name="code soort object ID",
            ),
        ),
        migrations.AlterField(
            model_name="onderwerpobject",
            name="onderwerpobjectidentificator_object_id",
            field=models.CharField(
                blank=True,
                help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.",
                max_length=200,
                verbose_name="object ID",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="bezoekadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="correspondentieadres_postcode",
            field=models.CharField(
                blank=True,
                help_text="Postcode van het adres (indien het een Nederlands adres betreft zonder BAG-id).",
                max_length=7,
                validators=[
                    openklant.utils.validators.CustomRegexValidator(
                        message="Postcode moet aan het volgende formaat voldoen: `1234 AB` (met spatie)",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
        ),
    ]
