# Generated by Django 4.2.20 on 2025-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0034_alter_betrokkene_bezoekadres_postcode_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="digitaaladres",
            name="unique_referentie_per_partij",
        ),
        migrations.AddConstraint(
            model_name="digitaaladres",
            constraint=models.UniqueConstraint(
                condition=models.Q(("referentie__gt", ""), ("partij__isnull", False)),
                fields=("partij", "referentie", "soort_digitaal_adres"),
                name="unique_referentie_per_partij_and_soort",
            ),
        ),
    ]
