# Generated by Django 5.2.3 on 2025-07-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "klantinteracties",
            "0035_remove_digitaaladres_unique_referentie_per_partij_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="partij",
            name="voorkeurs_digitaal_adres",
            field=models.ForeignKey(
                blank=True,
                help_text="'Partij' gaf voorkeur aan voor contact via 'Digitaal adres'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voorkeurs_partij",
                to="klantinteracties.digitaaladres",
                verbose_name="voorkeurs digitaal adres",
            ),
        ),
        migrations.AlterField(
            model_name="partij",
            name="voorkeurs_rekeningnummer",
            field=models.ForeignKey(
                blank=True,
                help_text="'Partij' gaf voorkeur voor 'rekeningnummer'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voorkeurs_rekeningnummer",
                to="klantinteracties.rekeningnummer",
                verbose_name="voorkeurs rekeningnummer",
            ),
        ),
    ]
