# Generated by Django 5.2.1 on 2025-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0036_alter_partij_voorkeurs_digitaal_adres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitaaladres",
            name="verificatie_datum",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Datum waarop het digitaal adres is geverifieerd.",
                null=True,
                verbose_name="verificatiedatum",
            ),
        ),
    ]
