# Generated by Django 5.2.3 on 2025-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0037_digitaaladres_verificatie_datum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partijidentificator",
            name="andere_partij_identificator",
            field=models.CharField(
                blank=True,
                help_text="Vrij tekstveld om de verwijzing naar een niet-voorgedefinieerd objecttype, soort objectID of Register vast te leggen. ",
                max_length=200,
                verbose_name="andere partij identificator",
            ),
        ),
    ]
