# Generated by Django 5.2.8 on 2025-12-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "klantinteracties",
            "0038_alter_partijidentificator_andere_partij_identificator",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaaladres",
            name="betrokkene",
            field=models.ForeignKey(
                blank=True,
                help_text="'Digitaal Adres' had 'Betrokkene bij klantcontact'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="klantinteracties.betrokkene",
                verbose_name="betrokkene",
            ),
        ),
    ]
