# Generated by Django 5.2.8 on 2026-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0039_alter_digitaaladres_betrokkene'),
    ]

    operations = [
        migrations.AddField(
            model_name='klantcontact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Generieke key/value metadata voor het klantcontact.', verbose_name='metadata'),
        ),
    ]
