# Generated by Django 5.2.8 on 2026-02-09 14:50

import openklant.components.klantinteracties.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0039_alter_digitaaladres_betrokkene'),
    ]

    operations = [
        migrations.AddField(
            model_name='klantcontact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Generieke key/value metadata voor het klantcontact.', validators=[openklant.components.klantinteracties.models.validators.validate_metadata], verbose_name='metadata'),
        ),
    ]
