# Generated by Django 5.2.11 on 2026-02-10 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0040_klantcontact_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetaak',
            name='referentienummer',
            field=models.CharField(blank=True, help_text='Uniek identificerend referentienummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke interne taak aan te duiden.', max_length=10, null=True, unique=True, validators=[django.core.validators.validate_integer], verbose_name='referentienummer'),
        ),
        migrations.AddField(
            model_name='klantcontact',
            name='referentienummer',
            field=models.CharField(blank=True, help_text='Uniek identificerend referentienummer dat tijdens communicatie tussen mensen kan worden gebruikt om het specifieke klantcontact aan te duiden.', max_length=10, null=True, unique=True, validators=[django.core.validators.validate_integer], verbose_name='referentienummer'),
        ),
        migrations.AlterField(
            model_name='internetaak',
            name='nummer',
            field=models.CharField(blank=True, help_text='**DEPRECATED** Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke interne taak aan te duiden.', max_length=10, null=True, unique=True, validators=[django.core.validators.validate_integer], verbose_name='nummer'),
        ),
        migrations.AlterField(
            model_name='klantcontact',
            name='nummer',
            field=models.CharField(blank=True, help_text='**DEPRECATED** Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om het specifieke klantcontact aan te duiden.', max_length=10, null=True, unique=True, validators=[django.core.validators.validate_integer], verbose_name='nummer'),
        ),
        migrations.AlterField(
            model_name='partij',
            name='nummer',
            field=models.CharField(blank=True, help_text='**DEPRECATED** Uniek identificerend nummer dat tijdens communicatie tussen mensen kan worden gebruikt om de specifieke partij aan te duiden.', max_length=10, null=True, unique=True, validators=[django.core.validators.validate_integer], verbose_name='nummer'),
        ),
    ]
