# Generated by Django 5.2.11 on 2026-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0041_internetaak_referentienummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klantcontact',
            name='reactie',
            field=models.TextField(blank=True, help_text='De reactie die die tijdens het contact werdt gegeven', max_length=1000, verbose_name='Reactie'),
        ),
        migrations.AlterField(
            model_name='klantcontact',
            name='inhoud',
            field=models.TextField(blank=True, help_text='Informatie die tijdens het klantcontact werd overgebracht of uitgewisseld, voor zover die voor betrokkenen of actoren relevant is. Via reactie kan optioneel het antwoord op de vraag worden opgeslagen.', max_length=1000, verbose_name='inhoud'),
        ),
    ]
