# Generated by Django 5.2.12 on 2026-04-09 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0042_klantcontact_reactie_alter_klantcontact_inhoud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partijidentificator",
            name="sub_identificator_van",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent PartijIdentificator under which this PartijIdentificator is unique (e.g. the parent identificator could specify a KVK number and the child identificator could specify a vestigingsnummer that is unique for the KVK number).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_partij_identificatoren",
                to="klantinteracties.partijidentificator",
                verbose_name="sub identificator van",
            ),
        ),
    ]
