# Generated by Django 5.2.12 on 2026-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0043_alter_partijidentificator_sub_identificator_van'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijlage',
            name='bijlageidentificator_code_objecttype',
            field=models.CharField(blank=True, help_text="Type van het object, bijvoorbeeld: 'DOCUMENT'.", max_length=200, verbose_name='code objecttype'),
        ),
        migrations.AlterField(
            model_name='bijlage',
            name='bijlageidentificator_code_register',
            field=models.CharField(blank=True, help_text="Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'open-zaak'.", max_length=200, verbose_name='code register'),
        ),
        migrations.AlterField(
            model_name='bijlage',
            name='bijlageidentificator_code_soort_object_id',
            field=models.CharField(blank=True, help_text="Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'uuid'.", max_length=200, verbose_name='code soort object ID'),
        ),
        migrations.AlterField(
            model_name='bijlage',
            name='bijlageidentificator_object_id',
            field=models.CharField(blank=True, help_text="Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '9193b03f-93c2-4bfc-badf-b61494bd31d6'.", max_length=200, verbose_name='object ID'),
        ),
    ]
