# Generated by Django 5.2.13 on 2026-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0044_alter_bijlage_bijlageidentificator_code_objecttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaaladres',
            name='is_standaard_adres',
            field=models.BooleanField(default=False, help_text='Geeft aan of dit digitaal adres het standaard adres is voor het `soortDigitaalAdres` voor de deze `partij`. Per `partij` en `soortDigitaalAdres` kan er maar één standaard adres zijn, zodra een ander adres gemarkeerd wordt met `isStandaardAdres=true` wordt `isStandaardAdres=false` gezet voor alle andere adressen met dezelfde `partij` en `soortDigitaalAdres`.', verbose_name='Is standaard adres'),
        ),
    ]
