# Generated by Django 5.2.12 on 2026-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0044_alter_bijlage_bijlageidentificator_code_objecttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klantcontact',
            name='hoofd_onderwerp_type',
            field=models.URLField(blank=True, help_text='Het type van het onderwerp van het contact', null=True, verbose_name='hoofd onderwerp type'),
        ),
        migrations.AddField(
            model_name='klantcontact',
            name='verdere_actie_ondernomen',
            field=models.BooleanField(blank=True, help_text='Geeft aan of het systeem waar het contact heeft plaats gevonden zelf actie onderneemt.', null=True, verbose_name='verdere actie ondernomen'),
        ),
    ]
