# Generated by Django 5.2.12 on 2026-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0045_alter_digitaaladres_is_standaard_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='klantcontact',
            name='hoofd_onderwerp_type',
            field=models.URLField(blank=True, help_text='Het type van het onderwerp van het contact', verbose_name='hoofd onderwerp type'),
        ),
        migrations.AddField(
            model_name='klantcontact',
            name='verdere_actie_ondernomen',
            field=models.BooleanField(blank=True, default=False, help_text='Geeft aan of het systeem waar het contact heeft plaats gevonden zelf actie onderneemt als het niet lukt om de klant te bereiken.', verbose_name='verdere actie ondernomen'),
        ),
    ]
