# Generated by Django 5.2.15 on 2026-07-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0045_alter_digitaaladres_is_standaard_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betrokkene',
            name='klantcontact',
            field=models.ForeignKey(help_text='Het klantcontact waar deze persoon of organisatie bij betrokken was.', on_delete=django.db.models.deletion.CASCADE, to='klantinteracties.klantcontact', verbose_name='klantcontact'),
        ),
        migrations.AlterField(
            model_name='betrokkene',
            name='partij',
            field=models.ForeignKey(blank=True, help_text='Betrokkene bij klantcontact die een partij was.', null=True, on_delete=django.db.models.deletion.CASCADE, to='klantinteracties.partij', verbose_name='partij'),
        ),
    ]
