# Generated by Django 5.2.15 on 2026-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klantinteracties", "0046_alter_betrokkene_klantcontact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klantcontact",
            name="reactie",
            field=models.TextField(
                blank=True,
                help_text="De reactie die die tijdens het contact werdt gegeven",
                max_length=4000,
                verbose_name="Reactie",
            ),
        ),
    ]
