# Generated by Django 5.2.15 on 2026-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klantinteracties', '0047_alter_klantcontact_reactie'),
    ]

    operations = [
        migrations.AddField(
            model_name='klantcontact',
            name='hoofd_onderwerp_type',
            field=models.URLField(blank=True, help_text='Het type van het onderwerp van het contact (bijvoorbeeld een zaaktype)', verbose_name='hoofd onderwerp type'),
        ),
        migrations.AddField(
            model_name='klantcontact',
            name='verdere_actie_ondernomen',
            field=models.BooleanField(blank=True, default=False, help_text='Geeft aan of het systeem waar het contact heeft plaats gevonden zelf actie onderneemt als het niet lukt om de klant te bereiken.', verbose_name='verdere actie ondernomen'),
        ),
        migrations.AddConstraint(
            model_name='klantcontact',
            constraint=models.CheckConstraint(condition=models.Q(('indicatie_contact_gelukt', True), ('verdere_actie_ondernomen', True), _negated=True), name='no_further_action_when_contact_succesful', violation_error_message='Als het contact gelukt is kan er geen verdere actie zijn ondernomen'),
        ),
    ]
