# Generated by Django 5.2.17 on 2026-09-21 09:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0048_klantcontact_hoofd_onderwerp_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internetakenactorenthoughmodel",
            options={
                "ordering": ("pk",),
                "verbose_name": "interne taak - toegewezen actor",
                "verbose_name_plural": "interne taken - toegewezen actoren",
            },
        ),
        migrations.AddField(
            model_name="organisatie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke (technische) identificatiecode van de organisatie.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke (technische) identificatiecode van de persoon.",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="internetakenactorenthoughmodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text=(
                    "Unieke (technische) identificatiecode van de toewijzing "
                    "van de interne taak aan de actor."
                ),
                unique=True,
            ),
        ),
    ]
