# Generated by Django 5.2.17 on 2026-10-05 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klantinteracties", "0048_klantcontact_hoofd_onderwerp_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internetakenactorenthoughmodel",
            options={
                "ordering": ("pk",),
                "verbose_name": "interne taak - toegewezen actor",
                "verbose_name_plural": "interne taken - toegewezen actoren",
            },
        ),
        migrations.AddField(
            model_name="internetakenactorenthoughmodel",
            name="uuid",
            field=models.UUIDField(
                help_text="Unieke (technische) identificatiecode van de toewijzing van de interne taak aan de actor.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organisatie",
            name="uuid",
            field=models.UUIDField(
                help_text="Unieke (technische) identificatiecode van de organisatie.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="persoon",
            name="uuid",
            field=models.UUIDField(
                help_text="Unieke (technische) identificatiecode van de persoon.",
                null=True,
            ),
        ),
        migrations.RunSQL(
            "UPDATE klantinteracties_internetakenactorenthoughmodel SET uuid = gen_random_uuid() WHERE uuid IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE klantinteracties_organisatie SET uuid = gen_random_uuid() WHERE uuid IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE klantinteracties_persoon SET uuid = gen_random_uuid() WHERE uuid IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="internetakenactorenthoughmodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke (technische) identificatiecode van de toewijzing van de interne taak aan de actor.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke (technische) identificatiecode van de organisatie.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="persoon",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unieke (technische) identificatiecode van de persoon.",
                unique=True,
            ),
        ),
    ]
