blank_issues_enabled: true
contact_links:
  - name: Ondersteuning met prioriteit / Priority support
    url: https://opengem.nl/contact/
    about: Neem direct contact met ons op / Contact us directly to get priority support.
