# Generated by Django 2.2.26 on 2022-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klanten", "0003_auto_20211217_0958"),
    ]

    operations = [
        migrations.AddField(
            model_name="klant",
            name="geverifieerd",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of de KLANT wel of niet geverifieerd is.",
            ),
        ),
    ]
