# Generated by Django 3.2.18 on 2023-09-05 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klanten", "0004_klant_geverifieerd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klant",
            name="klantnummer",
            field=models.CharField(
                help_text="De unieke identificatie van de klant binnen de bronorganisatie.",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        code="only-digits",
                        message="Waarde moet numeriek zijn.",
                        regex="^[0-9]+$",
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="klant",
            unique_together=set(),
        ),
    ]
