# Generated by Django 3.2.23 on 2023-12-21 19:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "locatie",
                    models.CharField(
                        help_text="Kort (40 karakters) tekstveld voor een omschrijving.",
                        max_length=40,
                        verbose_name="locatie",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "extern register",
                "verbose_name_plural": "externe registers",
            },
        ),
        migrations.CreateModel(
            name="Kanaal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Indicatie voor een waarde `Ja` of een waarde `Nee`.",
                        verbose_name="indicatie actief",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "kanaal",
                "verbose_name_plural": "kanalen",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "landcode",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="landcode",
                    ),
                ),
                (
                    "landnaam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="landnaam",
                    ),
                ),
                (
                    "ingangsdatum_land",
                    models.DateField(
                        help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21 representeert 21 februari 2022.",
                        verbose_name="ingangsdatum land",
                    ),
                ),
                (
                    "einddatum_land",
                    models.DateField(
                        help_text="Aanduiding van datum volgens de NEN-ISO 8601:2019-standaard. Een datum wordt genoteerd van het meest naar het minst significante onderdeel. Een voorbeeld: 2022-02-21 representeert 21 februari 2022.",
                        verbose_name="einddatum land",
                    ),
                ),
            ],
            options={
                "verbose_name": "land",
                "verbose_name_plural": "landen",
            },
        ),
        migrations.CreateModel(
            name="SoortDigitaalAdres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Indicatie voor een waarde `Ja` of een waarde `Nee`.",
                        verbose_name="indicatie actief",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "soort digitaal adres",
                "verbose_name_plural": "soorten digitaal adres",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoortObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Indicatie voor een waarde `Ja` of een waarde `Nee`.",
                        verbose_name="indicatie actief",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "soort object",
                "verbose_name_plural": "soorten object",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SoortObjectid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Indicatie voor een waarde `Ja` of een waarde `Nee`.",
                        verbose_name="indicatie actief",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "soort objectid",
                "verbose_name_plural": "soorten objectid",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Taal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke technische identificerende code, primair bedoeld voor gebruik bij interacties tussen IT-systemen.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "indicatie_actief",
                    models.BooleanField(
                        help_text="Indicatie voor een waarde `Ja` of een waarde `Nee`.",
                        verbose_name="indicatie actief",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Kort (80 karakters) tekstveld voor een naam.",
                        max_length=80,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "taal",
                "verbose_name_plural": "talen",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="land",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "einddatum_land__gte",
                        django.db.models.expressions.F("ingangsdatum_land"),
                    )
                ),
                name="eind_gte_ingang",
            ),
        ),
    ]
