# Generated by Django 2.2.24 on 2021-11-16 09:18

from django.contrib.contenttypes.models import ContentType
from django.core.management import call_command
from django.db import migrations


def forward(apps, schema_editor):
    from django.apps import apps as django_apps
    from django.contrib.contenttypes.management import create_contenttypes

    apps = django_apps.get_app_configs()

    for app in apps:
        for model in app.get_models():
            ct = ContentType.objects.get_for_model(model)
        create_contenttypes(app)

    call_command("loaddata", "default_admin_index.json")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("admin_index", "0006_auto_20230503_1910"),
        ("contactgegevens", "0001_initial"),
        ("klantinteracties", "0001_initial"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
