---

# From https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-otlp.yml
# and https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-docker.yml

global:
  scrape_interval: 15s
  evaluation_interval: 60s

# otlp:
#   # Recommended attributes to be promoted to labels.
#   promote_resource_attributes:
#     - service.instance.id
#     - service.name
#     - service.namespace
#     - cloud.availability_zone
#     - cloud.region
#     - container.name
#     - deployment.environment.name
#     - k8s.cluster.name
#     - k8s.container.name
#     - k8s.cronjob.name
#     - k8s.daemonset.name
#     - k8s.deployment.name
#     - k8s.job.name
#     - k8s.namespace.name
#     - k8s.pod.name
#     - k8s.replicaset.name
#     - k8s.statefulset.name
#   # Ingest OTLP data keeping all characters in metric/label names.
#   translation_strategy: NoUTF8EscapingWithSuffixes

# storage:
#   # OTLP is a push-based protocol, Out of order samples is a common scenario.
#   tsdb:
#     out_of_order_time_window: 30m

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'otel-collector'
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: /metrics
    metric_relabel_configs:
      # put the exported job (service name) in the job label
      - source_labels: ["exported_job"]
        regex: (.+)
        action: replace
        target_label: job
        replacement: $1
      # put the exported instance  in the instance label
      - source_labels: ["exported_instance"]
        regex: (.*)
        action: replace
        target_label: instance
        replacement: $1
      # remove cardinality on instance when the metric is global scope, this
      # effectively de-duplicates them.
      - source_labels: ["scope"]
        regex: global
        target_label: instance
        replacement: global
        action: replace
      # drop irrelevant labels:
      # - service_instance_id is equal to instance
      # - exported_instance duplicates instance
      # - exported_job is already assigned to job
      # - telemetry_sdk_version increases cardinality, but has little use
      - action: labeldrop
        regex: "^(service_instance_id|exported_instance|exported_job|telemetry_sdk_version)$"
