---

apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  jsonData:
    httpMethod: POST
    manageAlerts: false
    allowAsRecordingRulesTarget: false
    prometheusType: Prometheus
    prometheusVersion: 3.5.0
    cacheLevel: 'Low'
    disableRecordingRules: false
    timeInterval: 15s   # Prometheus scrape interval
    incrementalQueryOverlapWindow: 10m
