# Generated by Django 5.2.7 on 2025-11-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zgw_consumers', '0026_remove_service_oas_remove_service_oas_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentielijstenConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Geef aan of de optionele integratie met Referentielijsten API is ingeschakeld')),
                ('kanalen_tabel_code', models.CharField(blank=True, help_text='Code van de tabel die de kanaalopties bevat', max_length=100)),
                ('service', models.ForeignKey(help_text='De service waarmee referentielijstgegevens worden opgehaald', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgw_consumers.service')),
            ],
            options={
                'verbose_name': 'Referentielijsten configuration',
            },
        ),
    ]
