# Generated by Django 5.2.7 on 2025-12-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zgw_consumers', '0026_remove_service_oas_remove_service_oas_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentielijstenConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Indicates whether or not the optional Referentielijsten API integration is enabled')),
                ('kanalen_tabel_code', models.CharField(blank=True, help_text='Code of the `tabel` that contains the possible `kanalen` (channels)', max_length=100)),
                ('service', models.ForeignKey(help_text='The service used to retrieve information from the Referentielijsten API', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgw_consumers.service')),
            ],
            options={
                'verbose_name': 'Referentielijsten configuration',
            },
        ),
    ]
