# Generated by Django 5.2.7 on 2025-11-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('zgw_consumers', '0026_remove_service_oas_remove_service_oas_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentielijstenconfig',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether or not the optional Referentielijsten API integration is enabled'),
        ),
        migrations.AlterField(
            model_name='referentielijstenconfig',
            name='kanalen_tabel_code',
            field=models.CharField(blank=True, help_text='Code of the `tabel` that contains the possible `kanalen` (channels)', max_length=100),
        ),
        migrations.AlterField(
            model_name='referentielijstenconfig',
            name='service',
            field=models.ForeignKey(help_text='The service used to retrieve information from the Referentielijsten API', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgw_consumers.service'),
        ),
    ]
