# Generated by Django 2.2.24 on 2021-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactmomenten", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="klantcontactmoment",
            name="gelezen",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of het bericht gelezen is door de KLANT.",
            ),
        ),
    ]
