# Generated by Django 3.2.18 on 2023-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmomenten', '0002_klantcontactmoment_gelezen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmoment',
            name='antwoord',
            field=models.TextField(blank=True, help_text='Een toelichting die inhoudelijk de klantinteractie van de klant beschrijft. ***AFWIJKING:**', verbose_name='antwoord'),
        ),
        migrations.AddField(
            model_name='contactmoment',
            name='identificatie',
            field=models.CharField(blank=True, help_text='Unieke identificatie van het contactmoment. ***AFWIJKING:**', max_length=50, verbose_name='identificatie'),
        ),
        migrations.AddField(
            model_name='contactmoment',
            name='onderwerp',
            field=models.CharField(blank=True, help_text='Onderwerp van het contactmoment. ***AFWIJKING:**', max_length=255, verbose_name='onderwerp'),
        ),
        migrations.AddField(
            model_name='contactmoment',
            name='status',
            field=models.CharField(blank=True, choices=[('nieuw', 'Nieuw'), ('in_behandeling', 'In behandeling'), ('afgehandeld', 'Afgehandeld')], help_text='Status van het contactmoment. ***AFWIJKING:**', max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='contactmoment',
            name='type',
            field=models.CharField(blank=True, help_text='Type van het contactmoment. ***AFWIJKING:**', max_length=50, verbose_name='type'),
        ),
    ]
