# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------
import os
import sys

import django
from django.utils.translation import activate

sys.path.insert(0, os.path.abspath("../src"))
os.environ["LOG_REQUESTS"] = "false"

import openklant  # noqa isort:skip

# Import as private variable to avoid errors on build
from importlib.metadata import version as _version

from model_graph import generate_model_graphs

from openklant.setup import setup_env  # noqa isort:skip

setup_env()
django.setup()

# -- Project information -----------------------------------------------------

project = "Open Klant"
copyright = "2023, Maykin Media"
author = openklant.__author__

# The full version, including alpha/beta/rc tags
release = openklant.__version__


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autodoc",
    "sphinx.ext.graphviz",
    "django_setup_configuration.documentation.setup_config_example",
    "django_setup_configuration.documentation.setup_config_usage",
    "vng_api_common.uml_images",
    "sphinx_tabs.tabs",
    "recommonmark",
    # "sphinx_markdown_tables",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# Also set the language to English for Django, to make sure that any translatable text
# is also shown in English (for instance the help texts for setup configuration examples)
activate("en")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".pytest_cache", "_archive"]

source_suffix = [".rst", ".md"]

intersphinx_mapping = {
    "requests": (
        "https://docs.python-requests.org/en/latest/",
        None,
    ),
    "django": (
        "http://docs.djangoproject.com/en/4.2/",
        "http://docs.djangoproject.com/en/4.2/_objects/",
    ),
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_logo = "logo.svg"
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "theme_overrides.css",  # override wide tables with word wrap
]

todo_include_todos = True

linkcheck_retries = 3

linkcheck_ignore = [
    r"urn:*",
    r"https?://.*\.gemeente.nl",
    r"http://localhost:\d+/",
    r"https://.*sentry.*",
    r"https://example.com*",
    r"https://portal.azure.com*",
    r"https://.*kvk\.nl*",
    r"https://gdpr.eu*",
]

extlinks = {
    "open-klant": ("https://github.com/maykinmedia/open-klant/issues/%s", "#%s"),
    "open-api-framework": (
        "https://github.com/maykinmedia/open-api-framework/issues/%s",
        "#%s",
    ),
    "charts": (
        "https://github.com/maykinmedia/charts/issues/%s",
        "#%s",
    ),
}

django_structlog_version = _version("django-structlog")
intersphinx_mapping = {
    "django-structlog": (
        f"https://django-structlog.readthedocs.io/en/{django_structlog_version}",
        None,
    ),
}


#
#   Datamodel image creation
#
graphviz_output_format = "png"


def setup(app):
    app.connect("builder-inited", generate_model_graphs)
