# Generated by Django 4.2.15 on 2024-12-04 14:38

import logging

from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.models.aggregates import Count

import openklant.components.token.validators
from openklant.components.token.utils import get_token

logger = logging.getLogger(__name__)


def _generate_unique_identifiers(apps: StateApps, schema_editor) -> None:
    TokenAuth = apps.get_model("token", "TokenAuth")

    count = 1

    for token in TokenAuth.objects.filter(identifier__isnull=True):
        while TokenAuth.objects.filter(identifier=f"token-{count}").exists():
            count += 1

        identifier = f"token-{count}"
        logger.debug(f"Generated {identifier} for token {token.pk}")

        token.identifier = identifier
        token.save(update_fields=("identifier",))


def _generate_unique_tokens(apps: StateApps, schema_editor) -> None:
    TokenAuth = apps.get_model("token", "TokenAuth")

    duplicate_token_values = (
        TokenAuth.objects.values("token")
        .annotate(Count("id"))
        .order_by()
        .filter(id__count__gt=1)
    )

    duplicate_tokens = TokenAuth.objects.filter(
        token__in=[item["token"] for item in duplicate_token_values]
    )

    existing_tokens = set(
        TokenAuth.objects.exclude(
            id__in=[token.id for token in duplicate_tokens]
        ).values_list("token", flat=True)
    )

    for token in duplicate_tokens:
        _token: str = get_token(existing_tokens=existing_tokens)

        logger.debug(f"Generated a new token for {token.pk}")

        token.token = _token
        token.save(update_fields=("token",))

        existing_tokens.add(token)


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenauth",
            name="identifier",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=_generate_unique_identifiers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=_generate_unique_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(max_length=40, unique=True, verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="identifier",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="identifier",
            field=models.SlugField(
                help_text="A human-friendly label to refer to this token", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[openklant.components.token.validators.validate_whitespace],
                verbose_name="token",
            ),
        ),
    ]
