# Generated by Django 4.2.15 on 2024-12-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("token", "0002_tokenauth_identifier_alter_tokenauth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauth",
            name="identifier",
            field=models.SlugField(
                help_text="A human-friendly label to refer to this token", unique=True
            ),
        ),
    ]
