# Generated by Django 4.2.15 on 2024-12-04 09:43

from django.db import migrations, models
import openklant.components.token.validators


class Migration(migrations.Migration):

    dependencies = [
        ("token", "0003_alter_tokenauth_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[
                    openklant.components.token.validators.validate_whitespace
                ],
                verbose_name="token",
            ),
        ),
    ]
