name: generate-postman-collection

on:
  push:
    paths:
      - "src/openklant/components/*/openapi.yaml"
      - ".github/workflows/generate-postman-collection.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-generate-postman-collection:
    uses: maykinmedia/open-api-workflows/.github/workflows/generate-postman-collection.yml@v1
    strategy:
      matrix:
        component:
          - contactgegevens
          - klantinteracties
    with:
      schema-path: 'src/openklant/components/${{ matrix.component }}/openapi.yaml'
