name: lint-oas

on:
  push:
    paths:
      - "src/openklant/components/*/openapi.yaml"
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-lint-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/lint-oas.yml@v5
    strategy:
      matrix:
        component:
          - contactgegevens
          - klantinteracties
    with:
      schema-path: 'src/openklant/components/${{ matrix.component }}/openapi.yaml'
